// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Skill 是一次扫描结果的 Skill 元信息。
 */
export class Skill {
    "name": string;
    "description": string;
    "category": string;
    "source": string;

    /**
     * HasScripts 是否含 scripts/（可执行内容），供风险面摘要展示。
     */
    "hasScripts": boolean;

    /**
     * FileCount 制品文件数（风险面摘要展示用）。
     */
    "fileCount": number;

    /** Creates a new Skill instance. */
    constructor($$source: Partial<Skill> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("hasScripts" in $$source)) {
            this["hasScripts"] = false;
        }
        if (!("fileCount" in $$source)) {
            this["fileCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Skill instance from a string or object.
     */
    static createFrom($$source: any = {}): Skill {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Skill($$parsedSource as Partial<Skill>);
    }
}
