// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config 是 LLM 配置：供应商 + 模型条目注册表 + 当前激活条目。
 * 
 * Providers/Models 以 map 存储，map key 即条目 ID（YAML/JSON 中同样以
 * key 表达，条目结构内的 ID 字段不参与 YAML 序列化，避免双写）。
 * Validate 会把条目内的 ID 归一化为 map key（条件写入，不触碰已一致的
 * 共享条目）。Config 在发布后不可变（整体替换语义），map 查找无并发问题。
 */
export class Config {
    /**
     * 当前使用的 ModelConfig.EntryID
     */
    "active"?: string;
    "providers"?: { [_ in string]?: ProviderConfig | null };
    "models"?: { [_ in string]?: ModelConfig | null };

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField1_0($$parsedSource["providers"]);
        }
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField2_0($$parsedSource["models"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * ModelConfig 是一个可用模型条目。
 * EntryID 不进 YAML——文件中 map key 即条目 ID，Validate 时归一化回填。
 */
export class ModelConfig {
    /**
     * 形式，如 "gemini/gemini-3.1-flash-lite"。与 ModelId（发给 API 的
     * 真实模型名）区分：同一真实模型可配多个条目。
     */
    "entryId": string;

    /**
     * 引用 ProviderConfig.ID
     */
    "provider": string;

    /**
     * ModelId 发送给 API 的模型名。注意 ark 类型填的是推理接入点 endpoint ID（ep-xxx）。
     */
    "modelId": string;

    /**
     * 以下计量字段用于状态栏展示与费用估算
     */
    "contextWindow"?: number;
    "inputPricePerMillion"?: number;
    "outputPricePerMillion"?: number;

    /**
     * MaxTokens 最大输出 tokens：claude 必填；deepseek 默认 4096 上限 8192；其余可选。
     */
    "maxTokens"?: number;

    /**
     * ThinkingBudget 思考预算（仅 gemini）：nil 默认 / -1 动态 / 0 关闭 / >0 固定预算
     */
    "thinkingBudget"?: number | null;

    /**
     * EnableThinking 思考模式总开关（仅 deepseek/qwen/ark/ollama）：
     * nil 跟随服务端默认；true/false 显式开/关
     * （映射：deepseek ThinkingConfig.type、qwen enable_thinking、
     * ark Thinking.type、ollama ThinkValue）
     */
    "enableThinking"?: boolean | null;

    /** Creates a new ModelConfig instance. */
    constructor($$source: Partial<ModelConfig> = {}) {
        if (!("entryId" in $$source)) {
            this["entryId"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("modelId" in $$source)) {
            this["modelId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelConfig($$parsedSource as Partial<ModelConfig>);
    }
}

/**
 * ProviderConfig 是一个模型供应商的接入配置。
 * ID 不进 YAML——文件中 map key 即 ID，Validate 时归一化回填。
 */
export class ProviderConfig {
    /**
     * 唯一键（= providers map 的 key），如 "gemini"
     */
    "id": string;

    /**
     * 见 ProviderXxx 常量
     */
    "type": string;
    "apiKey"?: string;

    /**
     * BaseUrl 可覆盖官方端点（openai/qwen 类型必填；ollama 默认 http://localhost:11434）
     */
    "baseUrl"?: string;

    /**
     * AccessKey/SecretKey 千帆（qianfan）类型的 AK/SK 鉴权
     * （该 SDK 走全局单例配置，构建时注入）。
     */
    "accessKey"?: string;
    "secretKey"?: string;

    /**
     * Region 火山引擎区域（ark 类型），默认 cn-beijing。
     */
    "region"?: string;

    /**
     * CacheTTL Claude 自动前缀缓存（claude 类型）："5m"/"1h"，
     * 非空时在 system、工具定义与每轮最后一条 user 消息上自动打缓存断点。
     */
    "cacheTTL"?: string;

    /** Creates a new ProviderConfig instance. */
    constructor($$source: Partial<ProviderConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderConfig($$parsedSource as Partial<ProviderConfig>);
    }
}

// Private type creation functions
const $$createType0 = ProviderConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = ModelConfig.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Map($Create.Any, $$createType4);
