// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    "tierFullMax"?: number;
    "tierResidentMax"?: number;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}

export class SkillMeta {
    "name": string;
    "description": string;
    "category": string;
    "source": string;
    "upstreamVersion"?: string;
    "installedAt"?: string;
    "hasScripts": boolean;
    "fileCount": number;

    /**
     * Enabled 为 false 时技能对 Agent 完全不可见（索引/检索/加载均排除），
     * 文件与注册表条目保留，可随时恢复——与卸载的区别仅在于可逆。
     * 无 omitempty：开/关状态都显式落盘（兼容见 UnmarshalYAML）。
     */
    "enabled": boolean;

    /** Creates a new SkillMeta instance. */
    constructor($$source: Partial<SkillMeta> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("hasScripts" in $$source)) {
            this["hasScripts"] = false;
        }
        if (!("fileCount" in $$source)) {
            this["fileCount"] = 0;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillMeta($$parsedSource as Partial<SkillMeta>);
    }
}
