// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * NewTracerForSession 按当前全局追踪配置创建新 tracer
 * TraceConfig controls OpenTelemetry span export.
 * Spans are only exported to the configured OTLP collectors; there is no
 * local file sink. Enabled=false (the default when absent) disables all
 * tracing regardless of configured endpoints.
 */
export class TraceConfig {
    /**
     * Enabled is the master switch for tracing. Absent/false = 不产生任何 span。
     */
    "enabled"?: boolean;

    /**
     * OTLPHTTPEndpoint exports spans to an OTLP/HTTP collector
     * (e.g. "localhost:4318" for Jaeger). Empty disables this exporter.
     */
    "otlpHttpEndpoint"?: string;

    /**
     * OTLPGrpcEndpoint exports spans to an OTLP/gRPC collector
     * (e.g. "localhost:4317" for Arize Phoenix). Empty disables this exporter.
     */
    "otlpGrpcEndpoint"?: string;

    /** Creates a new TraceConfig instance. */
    constructor($$source: Partial<TraceConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TraceConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TraceConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TraceConfig($$parsedSource as Partial<TraceConfig>);
    }
}
