// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentsMDService —— AGENTS.md 项目指令记忆的可发现性入口（状态查询与骨架创建）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateAgentsMd 在工作区根写入 AGENTS.md 骨架模板；已存在时拒绝
 * （防覆盖用户内容——创建动作必须显式且幂等失败可见）。
 */
export function CreateAgentsMd(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2277195437, sessionID);
}

/**
 * GetAgentsMdStatus 报告会话工作区根是否存在 AGENTS.md。
 */
export function GetAgentsMdStatus(sessionID: string): $CancellablePromise<$models.AgentsMdStatus | null> {
    return $Call.ByID(1097388647, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AgentsMdStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
