// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService exposes the agent backend to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} conversationID
 * @returns {$CancellablePromise<void>}
 */
export function CancelMessage(conversationID) {
    return $Call.ByID(813006285, conversationID);
}

/**
 * @returns {$CancellablePromise<$models.Conversation | null>}
 */
export function CreateConversation() {
    return $Call.ByID(3097528975).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConversation(id) {
    return $Call.ByID(1908937864, id);
}

/**
 * DeleteMessage 删除指定消息及其之后的所有消息（undo to here）。
 * 同步更新内存和 session.jsonl。如果会话正在流式生成则拒绝删除。
 * @param {string} conversationID
 * @param {string} messageID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMessage(conversationID, messageID) {
    return $Call.ByID(1792683014, conversationID, messageID);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Conversation | null>}
 */
export function GetConversation(id) {
    return $Call.ByID(754590447, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetWorkspaceInfo returns the current workspace info for a conversation.
 * @param {string} conversationID
 * @returns {$CancellablePromise<$models.WorkspaceInfo | null>}
 */
export function GetWorkspaceInfo(conversationID) {
    return $Call.ByID(3454358245, conversationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Conversation[]>}
 */
export function ListConversations() {
    return $Call.ByID(2342191952).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListWorkspaceFiles returns a recursive file tree of the given conversation's
 * workspace directory. The workspace dir is per-conversation: {workDir}/conversations/{id}/workspace/.
 * If the directory doesn't exist yet (new conversation), an empty slice is returned.
 * @param {string} conversationID
 * @returns {$CancellablePromise<$models.FileEntry[]>}
 */
export function ListWorkspaceFiles(conversationID) {
    return $Call.ByID(2376334908, conversationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * OpenDirectoryDialog shows the OS native directory picker and returns the
 * selected path (empty string if the user cancels). This does NOT change the
 * conversation's workspace — call SetWorkspaceDir to apply the selection.
 * @returns {$CancellablePromise<string>}
 */
export function OpenDirectoryDialog() {
    return $Call.ByID(3054993619);
}

/**
 * OpenFile opens a file with the OS default application (not hardcoded to any
 * specific editor). The path should be relative to the conversation's workspace.
 * @param {string} conversationID
 * @param {string} relPath
 * @returns {$CancellablePromise<void>}
 */
export function OpenFile(conversationID, relPath) {
    return $Call.ByID(2435973242, conversationID, relPath);
}

/**
 * @param {string} id
 * @param {string} title
 * @returns {$CancellablePromise<void>}
 */
export function RenameConversation(id, title) {
    return $Call.ByID(258758085, id, title);
}

/**
 * RevealFileInExplorer reveals a specific file in the OS file manager
 * (selects the file in Explorer/Finder). The path should be relative to the
 * conversation's workspace.
 * @param {string} conversationID
 * @param {string} relPath
 * @returns {$CancellablePromise<void>}
 */
export function RevealFileInExplorer(conversationID, relPath) {
    return $Call.ByID(3485873987, conversationID, relPath);
}

/**
 * RevealInExplorer opens the OS file manager at the conversation's workspace
 * directory. On Windows this is Explorer, on macOS Finder, on Linux the
 * default file manager via xdg-open.
 * @param {string} conversationID
 * @returns {$CancellablePromise<void>}
 */
export function RevealInExplorer(conversationID) {
    return $Call.ByID(3758436925, conversationID);
}

/**
 * SendMessage 是 Agent 的入口。
 * @param {string} conversationID
 * @param {string} text
 * @returns {$CancellablePromise<$models.Message | null>}
 */
export function SendMessage(conversationID, text) {
    return $Call.ByID(729126489, conversationID, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * SetWorkspaceDir sets a custom workspace directory for the given conversation.
 * All subsequent agent file operations will operate within this directory.
 * Pass an empty string to reset to the default isolated workspace.
 * @param {string} conversationID
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function SetWorkspaceDir(conversationID, dir) {
    return $Call.ByID(3610152448, conversationID, dir);
}

// Private type creation functions
const $$createType0 = $models.Conversation.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.WorkspaceInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $models.FileEntry.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.Message.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
