// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as boot$0 from "./internal/boot/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "./internal/session/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnswerAskUser 提交一次询问/审批的用户答复。requestID 即工具调用 ID
 * （ask_user 询问或危险调用审批共用同一答复通道）。
 * value：confirm 为 "confirm"/"deny"；select 为选项 id；input 为文本；
 * 审批为 "allow"/"allow_always"/"deny"。reason 为可选拒绝理由。
 */
export function AnswerAskUser(requestID: string, value: string, reason: string): $CancellablePromise<void> {
    return $Call.ByID(2155695152, requestID, value, reason);
}

/**
 * CancelMessage cancels an in-flight SubmitMessage turn.
 */
export function CancelMessage(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(813006285, sessionID);
}

/**
 * CloseSession 关闭会话 Tab（仅视图标记：数据保留，可从已关闭列表重开）。
 */
export function CloseSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(1478965180, id);
}

/**
 * CreateProject 创建新项目（含一个默认会话，可直接开始对话）。
 * 返回 ProjectView：Sessions 恰含新建的那一个默认会话。
 */
export function CreateProject(): $CancellablePromise<boot$0.ProjectView | null> {
    return $Call.ByID(2602385197).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateSession 在既有项目中新建会话（会话 Tab，与项目共用工作区）。
 */
export function CreateSession(projectID: string): $CancellablePromise<session$0.Data | null> {
    return $Call.ByID(98051076, projectID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DeleteMessage deletes a message by ID — along with all messages after it
 * (truncate semantics, matching the frontend) — and returns its index.
 * Rejected while a turn is running: the message list is frozen mid-turn.
 */
export function DeleteMessage(sessionID: string, messageID: string): $CancellablePromise<number> {
    return $Call.ByID(1792683014, sessionID, messageID);
}

/**
 * DeleteProject 删除项目（级联其下全部会话数据）。
 */
export function DeleteProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(3732041524, id);
}

/**
 * DeleteSession 删除项目内的单个会话（真删除，清空对话记录）；
 * 删除整个项目用 DeleteProject。
 */
export function DeleteSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(3827341809, id);
}

/**
 * EditMessage edits a user message in-place (no regeneration).
 */
export function EditMessage(sessionID: string, messageID: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(847968623, sessionID, messageID, content);
}

export function GetSession(id: string): $CancellablePromise<session$0.Data | null> {
    return $Call.ByID(2463902692, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListProjects 列出全部项目（含各自会话）。
 */
export function ListProjects(): $CancellablePromise<(boot$0.ProjectView | null)[]> {
    return $Call.ByID(60175774).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * OpenSession 重新打开已关闭的会话 Tab。
 */
export function OpenSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(871953224, id);
}

/**
 * RenameProject 显式重命名项目（此后标题不再跟随会话自动命名）。
 */
export function RenameProject(id: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(3088019471, id, title);
}

export function RenameSession(id: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(1629291394, id, title);
}

/**
 * RetryMessage retries the last turn (or the turn containing the given
 * assistant message). It regenerates the assistant response for that turn.
 * 返回新一轮 assistant 消息 ID（前端回填本地占位，同 SubmitMessage）。
 */
export function RetryMessage(sessionID: string, messageID: string): $CancellablePromise<string> {
    return $Call.ByID(3966755125, sessionID, messageID);
}

/**
 * SubmitMessage submits a user message (with optional image data URLs)
 * and starts the agent loop.
 */
export function SubmitMessage(sessionID: string, content: string, images: string[]): $CancellablePromise<$models.SubmitResult | null> {
    return $Call.ByID(382211931, sessionID, content, images).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = boot$0.ProjectView.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = session$0.Data.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType1);
const $$createType5 = $models.SubmitResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
