// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService exposes the agent backend to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelMessage(conversationID: string): $CancellablePromise<void> {
    return $Call.ByID(813006285, conversationID);
}

export function CreateConversation(): $CancellablePromise<$models.Conversation | null> {
    return $Call.ByID(3097528975).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteConversation(id: string): $CancellablePromise<void> {
    return $Call.ByID(1908937864, id);
}

/**
 * DeleteMessage 删除指定消息及其之后的所有消息（undo to here）。
 * 同步更新内存和 session.jsonl。如果会话正在流式生成则拒绝删除。
 */
export function DeleteMessage(conversationID: string, messageID: string): $CancellablePromise<void> {
    return $Call.ByID(1792683014, conversationID, messageID);
}

/**
 * ExportConversation renders the conversation as Markdown, prompts the user
 * for a destination via the OS save dialog, and writes the file.
 * Returns the chosen path ("" if the user cancelled).
 */
export function ExportConversation(conversationID: string): $CancellablePromise<string> {
    return $Call.ByID(3425942425, conversationID);
}

export function GetConversation(id: string): $CancellablePromise<$models.Conversation | null> {
    return $Call.ByID(754590447, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetModelInfo 返回当前 LLM 配置的可公开信息。
 * 调用方无需会话上下文 —— 模型是应用级配置。
 */
export function GetModelInfo(): $CancellablePromise<$models.ModelInfo | null> {
    return $Call.ByID(708754981).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSessionStats 返回指定会话的聚合统计。空会话返回带模型/价格信息的零值。
 */
export function GetSessionStats(conversationID: string): $CancellablePromise<$models.SessionStats | null> {
    return $Call.ByID(520403183, conversationID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetWorkspaceInfo returns the current workspace info for a conversation.
 */
export function GetWorkspaceInfo(conversationID: string): $CancellablePromise<$models.WorkspaceInfo | null> {
    return $Call.ByID(3454358245, conversationID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListConversations(): $CancellablePromise<$models.Conversation[]> {
    return $Call.ByID(2342191952).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListWorkspaceFiles returns a recursive file tree of the given conversation's
 * workspace directory. The workspace dir is per-conversation: {workDir}/conversations/{id}/workspace/.
 * If the directory doesn't exist yet (new conversation), an empty slice is returned.
 */
export function ListWorkspaceFiles(conversationID: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(2376334908, conversationID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * OpenDirectoryDialog shows the OS native directory picker and returns the
 * selected path (empty string if the user cancels). This does NOT change the
 * conversation's workspace — call SetWorkspaceDir to apply the selection.
 */
export function OpenDirectoryDialog(): $CancellablePromise<string> {
    return $Call.ByID(3054993619);
}

/**
 * OpenFile opens a file with the OS default application (not hardcoded to any
 * specific editor). The path should be relative to the conversation's workspace.
 */
export function OpenFile(conversationID: string, relPath: string): $CancellablePromise<void> {
    return $Call.ByID(2435973242, conversationID, relPath);
}

export function RenameConversation(id: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(258758085, id, title);
}

/**
 * RetryMessage 重新生成最后一条 assistant 回复：重置该消息（清空内容与
 * 工具调用记录），丢弃其后的工具结果消息，重写 jsonl，然后重跑 Agent 循环。
 * 用于模型超时/出错后由用户发起的重试。会话正在流式生成时拒绝调用。
 */
export function RetryMessage(conversationID: string): $CancellablePromise<$models.Message | null> {
    return $Call.ByID(3966755125, conversationID).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * RevealFileInExplorer reveals a specific file in the OS file manager
 * (selects the file in Explorer/Finder). The path should be relative to the
 * conversation's workspace.
 */
export function RevealFileInExplorer(conversationID: string, relPath: string): $CancellablePromise<void> {
    return $Call.ByID(3485873987, conversationID, relPath);
}

/**
 * RevealInExplorer opens the OS file manager at the conversation's workspace
 * directory. On Windows this is Explorer, on macOS Finder, on Linux the
 * default file manager via xdg-open.
 */
export function RevealInExplorer(conversationID: string): $CancellablePromise<void> {
    return $Call.ByID(3758436925, conversationID);
}

/**
 * SendMessage 是 Agent 的入口。
 */
export function SendMessage(conversationID: string, text: string): $CancellablePromise<$models.Message | null> {
    return $Call.ByID(729126489, conversationID, text).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * SetWorkspaceDir sets a custom workspace directory for the given conversation.
 * All subsequent agent file operations will operate within this directory.
 * Pass an empty string to reset to the default isolated workspace.
 */
export function SetWorkspaceDir(conversationID: string, dir: string): $CancellablePromise<void> {
    return $Call.ByID(3610152448, conversationID, dir);
}

// Private type creation functions
const $$createType0 = $models.Conversation.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ModelInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.SessionStats.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.WorkspaceInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType0);
const $$createType9 = $models.FileEntry.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.Message.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
