// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "./internal/session/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelMessage cancels an in-flight SendMessage turn.
 */
export function CancelMessage(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(813006285, sessionID);
}

export function CreateSession(): $CancellablePromise<$models.Session | null> {
    return $Call.ByID(98051076).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteMessage deletes a message by ID and returns its index.
 */
export function DeleteMessage(sessionID: string, messageID: string): $CancellablePromise<number> {
    return $Call.ByID(1792683014, sessionID, messageID);
}

export function DeleteSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(3827341809, id);
}

/**
 * EditMessage edits a user message in-place (no regeneration).
 */
export function EditMessage(sessionID: string, messageID: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(847968623, sessionID, messageID, content);
}

/**
 * ExportSession renders the session as Markdown, prompts the user
 * for a destination via the OS save dialog, and writes the file.
 * Returns the chosen path ("" if the user cancelled).
 */
export function ExportSession(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(801229534, sessionID);
}

/**
 * GetAppConfig 返回当前配置（密钥原样返回，前端用眼睛按钮控制显示）。
 */
export function GetAppConfig(): $CancellablePromise<config$0.AppConfig | null> {
    return $Call.ByID(3243841041).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetModelInfo returns the currently active model (TopicBar/状态栏展示用）。
 * 未配置任何模型时返回空对象（前端退化为不显示）。
 */
export function GetModelInfo(): $CancellablePromise<$models.ModelInfo | null> {
    return $Call.ByID(708754981).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetSession(id: string): $CancellablePromise<$models.Session | null> {
    return $Call.ByID(2463902692, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSessionStats 返回指定会话的聚合统计。空会话返回带模型/价格信息的零值。
 */
export function GetSessionStats(sessionID: string): $CancellablePromise<$models.SessionStats | null> {
    return $Call.ByID(520403183, sessionID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetWorkspaceInfo returns the current workspace info for a session.
 */
export function GetWorkspaceInfo(sessionID: string): $CancellablePromise<$models.WorkspaceInfo | null> {
    return $Call.ByID(3454358245, sessionID).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListModels returns all configured model entries（TopicBar 切换下拉用）。
 * 按条目 ID 排序返回（map 无序，下拉列表需要确定性顺序）。
 */
export function ListModels(): $CancellablePromise<$models.ModelInfo[]> {
    return $Call.ByID(425219254).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListSessions(): $CancellablePromise<$models.Session[]> {
    return $Call.ByID(3651696153).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ListWorkspaceFiles returns a recursive file tree of the given session's
 * workspace directory. The workspace dir is per-session: {workDir}/sessions/{id}/workspace/.
 * If the directory doesn't exist yet (new session), an empty slice is returned.
 */
export function ListWorkspaceFiles(sessionID: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(2376334908, sessionID).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * OpenDirectoryDialog shows the OS native directory picker and returns the
 * selected path (empty string if the user cancels). This does NOT change the
 * session's workspace — call SetWorkspaceDir to apply the selection.
 */
export function OpenDirectoryDialog(): $CancellablePromise<string> {
    return $Call.ByID(3054993619);
}

/**
 * OpenFile opens a file with the OS default application (not hardcoded to any
 * specific editor). The path should be relative to the session's workspace.
 */
export function OpenFile(sessionID: string, relPath: string): $CancellablePromise<void> {
    return $Call.ByID(2435973242, sessionID, relPath);
}

export function RenameSession(id: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(1629291394, id, title);
}

/**
 * RetryMessage retries the last turn (or the turn containing the given
 * assistant message). It regenerates the assistant response for that turn.
 */
export function RetryMessage(sessionID: string, messageID: string): $CancellablePromise<void> {
    return $Call.ByID(3966755125, sessionID, messageID);
}

/**
 * RevealFileInExplorer reveals a specific file in the OS file manager
 * (selects the file in Explorer/Finder). The path should be relative to the
 * session's workspace.
 */
export function RevealFileInExplorer(sessionID: string, relPath: string): $CancellablePromise<void> {
    return $Call.ByID(3485873987, sessionID, relPath);
}

/**
 * RevealInExplorer opens the OS file manager at the session's workspace
 * directory. On Windows this is Explorer, on macOS Finder, on Linux the
 * default file manager via xdg-open.
 */
export function RevealInExplorer(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3758436925, sessionID);
}

/**
 * SaveAppConfig 校验并保存配置：写回 config.yaml（保留注释与 apiKey 引用），
 * 并热更新内存配置与模型注册表（model/agent/trace 立即生效，
 * workDir 需重启生效——工作目录涉及存量会话数据搬迁）。
 */
export function SaveAppConfig(v: config$0.AppConfig | null): $CancellablePromise<void> {
    return $Call.ByID(484951638, v);
}

/**
 * SendMessage sends a user message and starts the agent loop.
 */
export function SendMessage(sessionID: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(729126489, sessionID, content);
}

/**
 * SetActiveModel switches the active model: 预构建目标模型（失败则不切换），
 * 热更新注册表并落盘（active 键），最后广播 model:changed 事件。
 */
export function SetActiveModel(id: string): $CancellablePromise<void> {
    return $Call.ByID(1916297203, id);
}

/**
 * SetWorkspaceDir sets a custom workspace directory for the given session.
 * All subsequent agent file operations will operate within this directory.
 * Pass an empty string to reset to the default isolated workspace.
 */
export function SetWorkspaceDir(sessionID: string, dir: string): $CancellablePromise<void> {
    return $Call.ByID(3610152448, sessionID, dir);
}

// Private type creation functions
const $$createType0 = session$0.SessionState.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = config$0.AppConfig.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ModelInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.SessionStats.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.WorkspaceInfo.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType4);
const $$createType11 = $Create.Array($$createType0);
const $$createType12 = $models.FileEntry.createFrom;
const $$createType13 = $Create.Array($$createType12);
