// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CanvasService —— 画板素材库（Excalidraw Library）的持久化。
 * Excalidraw 组件默认把素材库存进 WebView 的 localStorage（埋在 WebView2
 * 用户数据目录深处，且随缓存清理丢失）；这里接管为 TARS 工作目录下的
 * 常规文件，与技能/记忆等数据同处。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CanvasInsertImage 画板窗口产出 PNG（dataURL）→ 广播给主窗口插入输入框。
 */
export function CanvasInsertImage(dataURL: string): $CancellablePromise<void> {
    return $Call.ByID(4260962165, dataURL);
}

/**
 * CanvasInsertMermaid 画板窗口产出 Mermaid 代码 → 广播给主窗口插入输入框。
 */
export function CanvasInsertMermaid(code: string): $CancellablePromise<void> {
    return $Call.ByID(3785857107, code);
}

/**
 * CloseAuxTab 关闭一个 Tab；最后一个 Tab 关闭时收起窗口（状态保留，
 * 再打开时恢复剩余标签）。
 */
export function CloseAuxTab(tabID: string): $CancellablePromise<void> {
    return $Call.ByID(2927238638, tabID);
}

/**
 * DetachAuxTab 把 Tab 从副面板拖出为独立小窗口（无边框同款样式），
 * 窗口出现在拖拽落点（屏幕坐标，以落点为窗口顶部中心）。
 */
export function DetachAuxTab(tabID: string, x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(3063043167, tabID, x, y);
}

/**
 * DropDetachedTab 独立窗口的 Tab 拖拽松开时调用：落点（屏幕坐标）在
 * 副面板窗口内则吸回为 Tab，否则保持独立悬浮。
 */
export function DropDetachedTab(tabID: string, x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(3452940709, tabID, x, y);
}

/**
 * ExportCanvasScene 另存为（Ctrl+Shift+S）：保存对话框导出 .excalidraw
 * 场景文件（可分享/备份，Excalidraw 原生格式）。返回保存路径，取消返回空串。
 */
export function ExportCanvasScene(jsonStr: string): $CancellablePromise<string> {
    return $Call.ByID(1458492969, jsonStr);
}

/**
 * GetAuxTabs 返回当前 Tab 列表与激活项（窗口加载时拉取）。
 */
export function GetAuxTabs(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1508126963).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetCanvasDraft 读取会话的画板草稿 JSON（不存在返回空串）。
 */
export function GetCanvasDraft(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(2215496290, sessionID);
}

/**
 * GetCanvasLibrary 返回素材库 JSON（Excalidraw LibraryItems 数组）。
 * 文件不存在返回 ""（前端视为空库）。
 */
export function GetCanvasLibrary(): $CancellablePromise<string> {
    return $Call.ByID(2629344522);
}

/**
 * ImportCanvasLibrary 拉取 .excalidrawlib URL 的素材并合并进本地素材库
 * （Excalidraw 网页版的 #addLibrary 安装协议在我们的嵌入组件里不可用：
 * 它把安装链接指向应用自身 origin，前端拦截后由这里代抓——避开
 * WebView 的 CORS 限制）。按素材 id 去重（已有素材保留本地版本）。
 * 返回合并后的完整素材库 JSON 与新增条数。
 */
export function ImportCanvasLibrary(sourceURL: string): $CancellablePromise<[string, number]> {
    return $Call.ByID(3310472743, sourceURL);
}

/**
 * OpenAuxTab 在副面板窗口打开（或激活）一个 Tab：kind 为 canvas / editor，
 * path 仅 editor 使用（工作区相对路径）。同 kind+path 的标签去重激活。
 */
export function OpenAuxTab(sessionID: string, kind: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(4012293328, sessionID, kind, path);
}

/**
 * OpenLibraryBrowser 在应用内窗口打开 Excalidraw 素材站点。
 * 一键安装链路的另一半：站点上点 "Add to Excalidraw" 会把窗口重定向到
 * <应用origin>/#addLibrary=<url>&token=...——外链在系统浏览器里不可达，
 * 但在本窗口里会加载回我们的前端，由启动早期的导入门（LibraryImportGate）
 * 接管 hash、完成导入并自动关窗。
 */
export function OpenLibraryBrowser(siteURL: string): $CancellablePromise<void> {
    return $Call.ByID(1781691816, siteURL);
}

/**
 * ReattachAuxTab 把独立窗口的 Tab 吸回副面板。
 */
export function ReattachAuxTab(tabID: string): $CancellablePromise<void> {
    return $Call.ByID(4047273116, tabID);
}

/**
 * RevealEditorRange 打开工作区文件（复用编辑器 Tab），定位到起始行并
 * 高亮 start~end 行。路径沿用 OpenAuxTab 的 confine 校验（在 FileViewer
 * 读取内容时生效）。
 */
export function RevealEditorRange(sessionID: string, path: string, startLine: number, endLine: number): $CancellablePromise<void> {
    return $Call.ByID(507815514, sessionID, path, startLine, endLine);
}

/**
 * SetCanvasDraft 保存会话的画板草稿（JSON object，含 elements/files/
 * 视口 appState；原子写；20MB 上限——图片走 files dataURL 可能较大）。
 */
export function SetCanvasDraft(sessionID: string, jsonStr: string): $CancellablePromise<void> {
    return $Call.ByID(3524040262, sessionID, jsonStr);
}

/**
 * SetCanvasLibrary 保存素材库 JSON（原子写：tmp + rename）。
 * 入参必须是合法 JSON 数组（Excalidraw LibraryItems）。
 */
export function SetCanvasLibrary(jsonStr: string): $CancellablePromise<void> {
    return $Call.ByID(2573279262, jsonStr);
}

/**
 * TakePendingReveal 拉取并清除某文件的待定位请求（FileViewer 挂载时调用）。
 * 返回值 [start, end]；无待处理请求时 ok=false。
 */
export function TakePendingReveal(path: string): $CancellablePromise<[number[], boolean]> {
    return $Call.ByID(2420835896, path).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
