// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CanvasService —— 画板素材库（Excalidraw Library）的持久化。
 * Excalidraw 组件默认把素材库存进 WebView 的 localStorage（埋在 WebView2
 * 用户数据目录深处，且随缓存清理丢失）；这里接管为 TARS 工作目录下的
 * 常规文件，与技能/记忆等数据同处。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetCanvasLibrary 返回素材库 JSON（Excalidraw LibraryItems 数组）。
 * 文件不存在返回 ""（前端视为空库）。
 */
export function GetCanvasLibrary(): $CancellablePromise<string> {
    return $Call.ByID(2629344522);
}

/**
 * ImportCanvasLibrary 拉取 .excalidrawlib URL 的素材并合并进本地素材库
 * （Excalidraw 网页版的 #addLibrary 安装协议在我们的嵌入组件里不可用：
 * 它把安装链接指向应用自身 origin，前端拦截后由这里代抓——避开
 * WebView 的 CORS 限制）。按素材 id 去重（已有素材保留本地版本）。
 * 返回合并后的完整素材库 JSON 与新增条数。
 */
export function ImportCanvasLibrary(sourceURL: string): $CancellablePromise<[string, number]> {
    return $Call.ByID(3310472743, sourceURL);
}

/**
 * OpenLibraryBrowser 在应用内窗口打开 Excalidraw 素材站点。
 * 一键安装链路的另一半：站点上点 "Add to Excalidraw" 会把窗口重定向到
 * <应用origin>/#addLibrary=<url>&token=...——外链在系统浏览器里不可达，
 * 但在本窗口里会加载回我们的前端，由启动早期的导入门（LibraryImportGate）
 * 接管 hash、完成导入并自动关窗。
 */
export function OpenLibraryBrowser(siteURL: string): $CancellablePromise<void> {
    return $Call.ByID(1781691816, siteURL);
}

/**
 * SetCanvasLibrary 保存素材库 JSON（原子写：tmp + rename）。
 * 入参必须是合法 JSON 数组（Excalidraw LibraryItems）。
 */
export function SetCanvasLibrary(jsonStr: string): $CancellablePromise<void> {
    return $Call.ByID(2573279262, jsonStr);
}
