// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService —— 应用配置的读取与保存（设置页通用页签）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";

/**
 * GetAppConfig 返回当前配置（密钥原样返回，前端用眼睛按钮控制显示）。
 */
export function GetAppConfig(): $CancellablePromise<config$0.AppConfig | null> {
    return $Call.ByID(2634732082).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveAppConfig 校验并保存配置：写回 config.yaml（保留注释与 apiKey 引用），
 * 并热更新内存配置与模型注册表（model/agent/trace 立即生效，
 * workDir 需重启生效——工作目录涉及存量会话数据搬迁）。
 */
export function SaveAppConfig(v: config$0.AppConfig | null): $CancellablePromise<void> {
    return $Call.ByID(827047463, v);
}

// Private type creation functions
const $$createType0 = config$0.AppConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
