// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExportService —— 会话导出（渲染 Markdown + 系统保存对话框）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ExportSession renders the session as Markdown, prompts the user
 * for a destination via the OS save dialog, and writes the file.
 * Returns the chosen path ("" if the user cancelled).
 */
export function ExportSession(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(1517483671, sessionID);
}

/**
 * SaveImage 把 data URL 图片保存到用户选择的位置（消息图片右键"保存图片"）。
 * 返回保存路径（"" 表示用户取消）。
 */
export function SaveImage(dataURL: string): $CancellablePromise<string> {
    return $Call.ByID(3890655751, dataURL);
}
