// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExportService —— 导出交互层：查找目标、弹系统对话框；
 * 渲染与落盘机制在 session 包（ExportMarkdown）与 schema 包（WriteImage）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ExportSession 导出会话为 Markdown：弹出系统保存对话框，
 * 用户确认后委托 session.ExportMarkdown 渲染并写盘。
 * 返回保存路径（"" 表示用户取消）。
 */
export function ExportSession(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(1517483671, sessionID);
}

/**
 * SaveImage 把 data URL 图片保存到用户选择的位置（消息图片右键"保存图片"）。
 * 解析扩展名用于对话框默认文件名；解析与落盘机制在 schema 包（WriteImage）。
 * 返回保存路径（"" 表示用户取消）。
 */
export function SaveImage(dataURL: string): $CancellablePromise<string> {
    return $Call.ByID(3890655751, dataURL);
}
