// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService —— 工作区文件树浏览与系统级打开/定位（工作区页面）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateWorkspaceEntry 新建文件或目录（父目录自动创建）。
 */
export function CreateWorkspaceEntry(sessionID: string, relPath: string, isDir: boolean): $CancellablePromise<void> {
    return $Call.ByID(3397491204, sessionID, relPath, isDir);
}

/**
 * DeleteWorkspaceEntry 删除文件或目录（目录递归删除；前端负责确认）。
 */
export function DeleteWorkspaceEntry(sessionID: string, relPath: string): $CancellablePromise<void> {
    return $Call.ByID(288716723, sessionID, relPath);
}

/**
 * InsertEditorReference 编辑器窗口框选引用（path:Lx-Ly）→ 广播给主窗口
 * 插入对话输入框（发送时由 Controller 展开为真实代码片段）。
 */
export function InsertEditorReference(sessionID: string, ref: string): $CancellablePromise<void> {
    return $Call.ByID(720907120, sessionID, ref);
}

/**
 * ListWorkspaceFiles returns a recursive file tree of the given session's
 * workspace directory（工作区是项目级：同项目多会话共享同一目录）。
 * If the directory doesn't exist yet (new project), an empty slice is returned.
 */
export function ListWorkspaceFiles(sessionID: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(267893223, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenFile opens a file with the OS default application (not hardcoded to any
 * specific editor). The path should be relative to the session's workspace.
 */
export function OpenFile(sessionID: string, relPath: string): $CancellablePromise<void> {
    return $Call.ByID(2444982985, sessionID, relPath);
}

/**
 * ReadWorkspaceFile 读取工作区文件内容（编辑器加载用）。超过 2MB 或
 * 内容含 NUL（二进制）时报错，引导用户用外部程序打开。
 */
export function ReadWorkspaceFile(sessionID: string, relPath: string): $CancellablePromise<string> {
    return $Call.ByID(3368951250, sessionID, relPath);
}

/**
 * RenameWorkspaceEntry 重命名/移动文件或目录。
 */
export function RenameWorkspaceEntry(sessionID: string, oldRel: string, newRel: string): $CancellablePromise<void> {
    return $Call.ByID(2335433450, sessionID, oldRel, newRel);
}

/**
 * RevealFileInExplorer reveals a specific file in the OS file manager
 * (selects the file in Explorer/Finder). The path should be relative to the
 * session's workspace.
 */
export function RevealFileInExplorer(sessionID: string, relPath: string): $CancellablePromise<void> {
    return $Call.ByID(532699112, sessionID, relPath);
}

/**
 * RevealInExplorer opens the OS file manager at the session's workspace
 * directory. On Windows this is Explorer, on macOS Finder, on Linux the
 * default file manager via xdg-open.
 */
export function RevealInExplorer(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2451653222, sessionID);
}

/**
 * RevealProjectWorkspace opens the OS file manager at the project's workspace
 * directory（项目级入口：零会话项目没有 Controller，直接经项目管理器解析）。
 */
export function RevealProjectWorkspace(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(3025360820, projectID);
}

/**
 * WriteWorkspaceFile 保存工作区文件（编辑器保存；不存在则创建）。
 */
export function WriteWorkspaceFile(sessionID: string, relPath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(973457633, sessionID, relPath, content);
}

// Private type creation functions
const $$createType0 = $models.FileEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
