// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService —— 工作区文件树浏览与系统级打开/定位（工作区页面）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListWorkspaceFiles returns a recursive file tree of the given session's
 * workspace directory（工作区是项目级：同项目多会话共享同一目录）。
 * If the directory doesn't exist yet (new project), an empty slice is returned.
 */
export function ListWorkspaceFiles(sessionID: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(267893223, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenFile opens a file with the OS default application (not hardcoded to any
 * specific editor). The path should be relative to the session's workspace.
 */
export function OpenFile(sessionID: string, relPath: string): $CancellablePromise<void> {
    return $Call.ByID(2444982985, sessionID, relPath);
}

/**
 * RevealFileInExplorer reveals a specific file in the OS file manager
 * (selects the file in Explorer/Finder). The path should be relative to the
 * session's workspace.
 */
export function RevealFileInExplorer(sessionID: string, relPath: string): $CancellablePromise<void> {
    return $Call.ByID(532699112, sessionID, relPath);
}

/**
 * RevealInExplorer opens the OS file manager at the session's workspace
 * directory. On Windows this is Explorer, on macOS Finder, on Linux the
 * default file manager via xdg-open.
 */
export function RevealInExplorer(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2451653222, sessionID);
}

/**
 * RevealProjectWorkspace opens the OS file manager at the project's workspace
 * directory（项目级入口：零会话项目没有 Controller，直接经项目管理器解析）。
 */
export function RevealProjectWorkspace(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(3025360820, projectID);
}

// Private type creation functions
const $$createType0 = $models.FileEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
