// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCPService —— MCP 服务器管理（设置页 MCP 页签）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcp$0 from "./pkg/mcp/models.js";

/**
 * ListMCPServers 返回全部已配置 MCP 服务器（含禁用项与工具计数）。
 */
export function ListMCPServers(): $CancellablePromise<(mcp$0.ServerInfo | null)[]> {
    return $Call.ByID(754977425).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListMCPTools 返回一个服务器的缓存工具清单（未探测返回空）。
 */
export function ListMCPTools(server: string): $CancellablePromise<(mcp$0.ToolInfo | null)[]> {
    return $Call.ByID(3313989138, server).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ProbeMCPServer 探测一个已启用服务器：拉起进程抓取工具清单并缓存
 * （此后会话启动零进程，discover_tools 用缓存检索）。
 * 服务器须已配置且启用；60s 超时（npx 类启动器首次下载可能较慢）。
 */
export function ProbeMCPServer(name: string): $CancellablePromise<void> {
    return $Call.ByID(1083674144, name);
}

/**
 * RemoveMCPServer 移除一个 MCP 服务器（立即落盘生效；连接即回收，
 * 探测缓存同步清理）。
 */
export function RemoveMCPServer(name: string): $CancellablePromise<void> {
    return $Call.ByID(4290480260, name);
}

/**
 * SetMCPServerEnabled 启用/禁用服务器（立即落盘生效；禁用后对 Agent
 * 不可见——索引/检索/连接排除，连接即回收，配置与探测缓存保留）。
 */
export function SetMCPServerEnabled(name: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3944286399, name, enabled);
}

/**
 * UpsertMCPServer 登记/覆盖一个 MCP 服务器（立即落盘生效；
 * 覆盖既有服务器时其运行中连接即回收，下次调用按新配置懒重启）。
 */
export function UpsertMCPServer(name: string, cfg: mcp$0.ServerConfig | null): $CancellablePromise<void> {
    return $Call.ByID(3653454213, name, cfg);
}

// Private type creation functions
const $$createType0 = mcp$0.ServerInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = mcp$0.ToolInfo.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
