// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MemoryService —— 记忆面板 API（设置页记忆页签：事实/候选/审计）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AdoptAllMemoryCandidates 批量采纳一个项目的全部候选（单条失败不阻断，
 * 返回首个错误——面板刷新后可见剩余项）。
 */
export function AdoptAllMemoryCandidates(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(3458060694, projectID);
}

/**
 * AdoptMemoryCandidate 采纳一条记忆候选：转为正式事实并移出候选区。
 */
export function AdoptMemoryCandidate(projectID: string, subject: string): $CancellablePromise<void> {
    return $Call.ByID(3241516268, projectID, subject);
}

/**
 * ForgetMemoryFact 删除一条记忆（归档留痕，可恢复）。
 */
export function ForgetMemoryFact(scope: string, projectID: string, subject: string): $CancellablePromise<void> {
    return $Call.ByID(2935642534, scope, projectID, subject);
}

/**
 * ListMemoryAudit 返回一个记忆根的审计视图（留痕不真删的可恢复性证明）。
 */
export function ListMemoryAudit(scope: string, projectID: string): $CancellablePromise<$models.MemoryAuditView | null> {
    return $Call.ByID(3859787056, scope, projectID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListMemoryFacts 列出全部记忆事实（全局 + 有事实的项目；含过期项——
 * 面板是审计界面，过期项由前端灰显标注）。
 */
export function ListMemoryFacts(): $CancellablePromise<$models.MemoryFactsView | null> {
    return $Call.ByID(763106652).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RejectAllMemoryCandidates 批量拒绝一个项目的全部候选。
 */
export function RejectAllMemoryCandidates(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(1520981761, projectID);
}

/**
 * RejectMemoryCandidate 拒绝一条记忆候选：移入拒绝审计（不再重复提议）。
 */
export function RejectMemoryCandidate(projectID: string, subject: string): $CancellablePromise<void> {
    return $Call.ByID(3676616287, projectID, subject);
}

/**
 * UpdateMemoryFact 编辑一条记忆的正文（旧值归档；敏感模式校验在存储层）。
 */
export function UpdateMemoryFact(scope: string, projectID: string, subject: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(3597305558, scope, projectID, subject, body);
}

// Private type creation functions
const $$createType0 = $models.MemoryAuditView.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.MemoryFactsView.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
