// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Conversation is a chat session with an ordered list of messages.
 */
export class Conversation {
    /**
     * Creates a new Conversation instance.
     * @param {Partial<Conversation>} [$$source = {}] - The source object to create the Conversation.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("messages" in $$source)) {
            /**
             * @member
             * @type {Message[]}
             */
            this["messages"] = [];
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conversation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Conversation}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField2_0($$parsedSource["messages"]);
        }
        return new Conversation(/** @type {Partial<Conversation>} */($$parsedSource));
    }
}

/**
 * ConversationRenamedEvent is the payload of the "conversation:renamed" event.
 */
export class ConversationRenamedEvent {
    /**
     * Creates a new ConversationRenamedEvent instance.
     * @param {Partial<ConversationRenamedEvent>} [$$source = {}] - The source object to create the ConversationRenamedEvent.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConversationRenamedEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConversationRenamedEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConversationRenamedEvent(/** @type {Partial<ConversationRenamedEvent>} */($$parsedSource));
    }
}

/**
 * FileEntry represents a single file or directory in the workspace file tree.
 */
export class FileEntry {
    /**
     * Creates a new FileEntry instance.
     * @param {Partial<FileEntry>} [$$source = {}] - The source object to create the FileEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * path relative to workspace root
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * file size in bytes (0 for dirs)
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FileEntry[] | undefined}
             */
            this["children"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileEntry}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField4_0($$parsedSource["children"]);
        }
        return new FileEntry(/** @type {Partial<FileEntry>} */($$parsedSource));
    }
}

/**
 * Message is a single chat message within a conversation.
 */
export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ToolCall[] | undefined}
             */
            this["toolCalls"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["toolCallId"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolCalls" in $$parsedSource) {
            $$parsedSource["toolCalls"] = $$createField3_0($$parsedSource["toolCalls"]);
        }
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

/**
 * ReasoningEvent is the payload of the "agent:reasoning" event: the model's
 * thinking process (reasoning content) for the current turn. Emitted when
 * the model returns ReasoningContent alongside its response.
 */
export class ReasoningEvent {
    /**
     * Creates a new ReasoningEvent instance.
     * @param {Partial<ReasoningEvent>} [$$source = {}] - The source object to create the ReasoningEvent.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("messageId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["messageId"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReasoningEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReasoningEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReasoningEvent(/** @type {Partial<ReasoningEvent>} */($$parsedSource));
    }
}

/**
 * StreamChunk is the payload of the "agent:chunk" event.
 */
export class StreamChunk {
    /**
     * Creates a new StreamChunk instance.
     * @param {Partial<StreamChunk>} [$$source = {}] - The source object to create the StreamChunk.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("messageId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["messageId"] = "";
        }
        if (!("chunk" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chunk"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamChunk instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StreamChunk}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamChunk(/** @type {Partial<StreamChunk>} */($$parsedSource));
    }
}

/**
 * StreamDone is the payload of the "agent:done" event.
 */
export class StreamDone {
    /**
     * Creates a new StreamDone instance.
     * @param {Partial<StreamDone>} [$$source = {}] - The source object to create the StreamDone.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("messageId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["messageId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {UsageInfo | null | undefined}
             */
            this["usage"] = undefined;
        }
        if (!("elapsedMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["elapsedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamDone instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StreamDone}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField2_0($$parsedSource["usage"]);
        }
        return new StreamDone(/** @type {Partial<StreamDone>} */($$parsedSource));
    }
}

/**
 * StreamError is the payload of the "agent:error" event.
 */
export class StreamError {
    /**
     * Creates a new StreamError instance.
     * @param {Partial<StreamError>} [$$source = {}] - The source object to create the StreamError.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("messageId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["messageId"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamError instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StreamError}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamError(/** @type {Partial<StreamError>} */($$parsedSource));
    }
}

/**
 * ToolCall 记录模型请求的一次工具调用。
 * Output 不参与持久化与 LLM 上下文构建，仅在 GetConversation 返回时
 * 从对应 tool 消息合并填充，供前端展示工具执行结果。
 */
export class ToolCall {
    /**
     * Creates a new ToolCall instance.
     * @param {Partial<ToolCall>} [$$source = {}] - The source object to create the ToolCall.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("args" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["args"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["output"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCall instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolCall}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCall(/** @type {Partial<ToolCall>} */($$parsedSource));
    }
}

/**
 * ToolEvent is the payload of the "agent:tool" event.
 */
export class ToolEvent {
    /**
     * Creates a new ToolEvent instance.
     * @param {Partial<ToolEvent>} [$$source = {}] - The source object to create the ToolEvent.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("messageId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["messageId"] = "";
        }
        if (!("toolCallId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toolCallId"] = "";
        }
        if (!("toolName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toolName"] = "";
        }
        if (!("args" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["args"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolEvent(/** @type {Partial<ToolEvent>} */($$parsedSource));
    }
}

/**
 * ToolResultEvent is the payload of the "agent:tool_result" event.
 */
export class ToolResultEvent {
    /**
     * Creates a new ToolResultEvent instance.
     * @param {Partial<ToolResultEvent>} [$$source = {}] - The source object to create the ToolResultEvent.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("messageId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["messageId"] = "";
        }
        if (!("toolCallId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toolCallId"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolResultEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolResultEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolResultEvent(/** @type {Partial<ToolResultEvent>} */($$parsedSource));
    }
}

/**
 * UsageInfo carries token usage statistics for the completed response.
 */
export class UsageInfo {
    /**
     * Creates a new UsageInfo instance.
     * @param {Partial<UsageInfo>} [$$source = {}] - The source object to create the UsageInfo.
     */
    constructor($$source = {}) {
        if (!("promptTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["promptTokens"] = 0;
        }
        if (!("completionTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completionTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageInfo(/** @type {Partial<UsageInfo>} */($$parsedSource));
    }
}

/**
 * WorkspaceChangedEvent is the payload of the "workspace:changed" event.
 */
export class WorkspaceChangedEvent {
    /**
     * Creates a new WorkspaceChangedEvent instance.
     * @param {Partial<WorkspaceChangedEvent>} [$$source = {}] - The source object to create the WorkspaceChangedEvent.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isCustom" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isCustom"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceChangedEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceChangedEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceChangedEvent(/** @type {Partial<WorkspaceChangedEvent>} */($$parsedSource));
    }
}

/**
 * WorkspaceInfo describes the current workspace state of a conversation.
 */
export class WorkspaceInfo {
    /**
     * Creates a new WorkspaceInfo instance.
     * @param {Partial<WorkspaceInfo>} [$$source = {}] - The source object to create the WorkspaceInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * Path is the effective workspace directory path.
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isCustom" in $$source)) {
            /**
             * IsCustom indicates whether the workspace is a user-chosen external
             * directory (true) or the default isolated workspace (false).
             * @member
             * @type {boolean}
             */
            this["isCustom"] = false;
        }
        if (!("name" in $$source)) {
            /**
             * Name is the base name of the workspace directory, for display.
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceInfo(/** @type {Partial<WorkspaceInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Message.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = FileEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ToolCall.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = UsageInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
