// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileEntry represents a single file or directory in the workspace file tree.
 */
export class FileEntry {
    "name": string;

    /**
     * path relative to workspace root
     */
    "path": string;
    "isDir": boolean;

    /**
     * file size in bytes (0 for dirs)
     */
    "size": number;
    "children"?: FileEntry[];

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField4_0($$parsedSource["children"]);
        }
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

/**
 * ModelChangedEvent is the payload of the "model:changed" event.
 */
export class ModelChangedEvent {
    "model": ModelInfo;

    /** Creates a new ModelChangedEvent instance. */
    constructor($$source: Partial<ModelChangedEvent> = {}) {
        if (!("model" in $$source)) {
            this["model"] = (new ModelInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelChangedEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelChangedEvent {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("model" in $$parsedSource) {
            $$parsedSource["model"] = $$createField0_0($$parsedSource["model"]);
        }
        return new ModelChangedEvent($$parsedSource as Partial<ModelChangedEvent>);
    }
}

/**
 * ModelInfo describes one configured model entry.
 */
export class ModelInfo {
    /**
     * 配置条目 ID（models[].entryId）
     */
    "entryId": string;

    /**
     * 供应商 ID
     */
    "provider": string;

    /**
     * 供应商类型（gemini/openai）
     */
    "providerType": string;

    /**
     * 发送给 API 的真实模型名
     */
    "modelId": string;

    /**
     * 上下文窗口大小（tokens），0 = 未知
     */
    "contextWindow": number;

    /**
     * 是否为当前使用中的模型
     */
    "active": boolean;

    /** Creates a new ModelInfo instance. */
    constructor($$source: Partial<ModelInfo> = {}) {
        if (!("entryId" in $$source)) {
            this["entryId"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("providerType" in $$source)) {
            this["providerType"] = "";
        }
        if (!("modelId" in $$source)) {
            this["modelId"] = "";
        }
        if (!("contextWindow" in $$source)) {
            this["contextWindow"] = 0;
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelInfo($$parsedSource as Partial<ModelInfo>);
    }
}

/**
 * ModelPrice 是单个模型条目的价格表（元/百万 tokens）。
 */
export class ModelPrice {
    "input": number;
    "output": number;

    /** Creates a new ModelPrice instance. */
    constructor($$source: Partial<ModelPrice> = {}) {
        if (!("input" in $$source)) {
            this["input"] = 0;
        }
        if (!("output" in $$source)) {
            this["output"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelPrice instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelPrice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelPrice($$parsedSource as Partial<ModelPrice>);
    }
}

/**
 * SessionStats 是会话级聚合统计，供底部状态栏展示。
 * 轮次级指标（本次命中率/本次费用/tokens/耗时）随每条 assistant 消息的
 * Usage/ElapsedMs 持久化，由前端在消息底部直接渲染，不在此聚合。
 */
export class SessionStats {
    /**
     * ModelID 当前使用的模型名。
     */
    "modelId": string;

    /**
     * ModelHealthy 最近一次 LLM 调用是否成功（状态栏绿/红灯）。
     */
    "modelHealthy": boolean;

    /**
     * Rounds 会话轮次（user 消息数）。
     */
    "rounds": number;

    /**
     * TotalTokens 会话累计 token（所有 assistant 回复合计）。
     */
    "totalTokens": number;

    /**
     * TotalCredits 会话累计 Credits（1 credit = 1000 tokens，直观量级指标）。
     */
    "totalCredits": number;

    /**
     * TotalCostYuan 会话累计费用（元），按各轮模型条目的价格表估算。
     */
    "totalCostYuan": number;

    /**
     * AvgCacheHitRate 会话平均缓存命中率 = Σcached / Σprompt（0-1）。
     */
    "avgCacheHitRate": number;

    /**
     * ContextUsage 上下文使用占比 = 最近一次请求的 promptTokens / ContextWindow（0-1）。
     */
    "contextUsage": number;

    /**
     * ContextWindow 模型上下文窗口（tokens），供前端展示 "x/y" 形式。
     */
    "contextWindow": number;

    /**
     * CompressionThreshold 压缩阈值配置（0-1）。
     */
    "compressionThreshold": number;

    /**
     * 当前激活模型的价格表，透传给前端计算每条消息的"本次费用"。
     */
    "inputPricePerMillion": number;
    "outputPricePerMillion": number;

    /**
     * ModelPrices 全部模型条目的价格表（key = 条目 ID）：
     * 前端按每条消息的 usage.entryId 核算单条费用；
     * 条目被删除时回退激活模型价格（费用是估算值而非账单）。
     */
    "modelPrices"?: { [_ in string]?: ModelPrice };

    /** Creates a new SessionStats instance. */
    constructor($$source: Partial<SessionStats> = {}) {
        if (!("modelId" in $$source)) {
            this["modelId"] = "";
        }
        if (!("modelHealthy" in $$source)) {
            this["modelHealthy"] = false;
        }
        if (!("rounds" in $$source)) {
            this["rounds"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }
        if (!("totalCredits" in $$source)) {
            this["totalCredits"] = 0;
        }
        if (!("totalCostYuan" in $$source)) {
            this["totalCostYuan"] = 0;
        }
        if (!("avgCacheHitRate" in $$source)) {
            this["avgCacheHitRate"] = 0;
        }
        if (!("contextUsage" in $$source)) {
            this["contextUsage"] = 0;
        }
        if (!("contextWindow" in $$source)) {
            this["contextWindow"] = 0;
        }
        if (!("compressionThreshold" in $$source)) {
            this["compressionThreshold"] = 0;
        }
        if (!("inputPricePerMillion" in $$source)) {
            this["inputPricePerMillion"] = 0;
        }
        if (!("outputPricePerMillion" in $$source)) {
            this["outputPricePerMillion"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionStats instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionStats {
        const $$createField12_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modelPrices" in $$parsedSource) {
            $$parsedSource["modelPrices"] = $$createField12_0($$parsedSource["modelPrices"]);
        }
        return new SessionStats($$parsedSource as Partial<SessionStats>);
    }
}

/**
 * WorkspaceChangedEvent is the payload of the "workspace:changed" event.
 */
export class WorkspaceChangedEvent {
    "sessionId": string;
    "path": string;
    "isCustom": boolean;

    /** Creates a new WorkspaceChangedEvent instance. */
    constructor($$source: Partial<WorkspaceChangedEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isCustom" in $$source)) {
            this["isCustom"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceChangedEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceChangedEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceChangedEvent($$parsedSource as Partial<WorkspaceChangedEvent>);
    }
}

/**
 * WorkspaceInfo describes the current workspace state of a session.
 */
export class WorkspaceInfo {
    /**
     * Path is the effective workspace directory path.
     */
    "path": string;

    /**
     * IsCustom indicates whether the workspace is a user-chosen external
     * directory (true) or the default isolated workspace (false).
     */
    "isCustom": boolean;

    /**
     * Name is the base name of the workspace directory, for display.
     */
    "name": string;

    /** Creates a new WorkspaceInfo instance. */
    constructor($$source: Partial<WorkspaceInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isCustom" in $$source)) {
            this["isCustom"] = false;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceInfo($$parsedSource as Partial<WorkspaceInfo>);
    }
}

// Private type creation functions
const $$createType0 = FileEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ModelInfo.createFrom;
const $$createType3 = ModelPrice.createFrom;
const $$createType4 = $Create.Map($Create.Any, $$createType3);
