// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModelService —— 模型条目查询与激活切换（TopicBar/设置页模型页签）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetModelInfo returns the currently active model (TopicBar/状态栏展示用）。
 * 未配置任何模型时返回空对象（前端退化为不显示）。
 */
export function GetModelInfo(): $CancellablePromise<$models.ModelInfo | null> {
    return $Call.ByID(1339323181).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListModels returns all configured model entries（TopicBar 切换下拉用）。
 * 按条目 ID 排序返回（map 无序，下拉列表需要确定性顺序）。
 */
export function ListModels(): $CancellablePromise<$models.ModelInfo[]> {
    return $Call.ByID(1026790542).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SetActiveModel switches the active model: 预构建目标模型（失败则不切换），
 * 热更新注册表并落盘（active 键），最后广播 model:changed 事件。
 */
export function SetActiveModel(id: string): $CancellablePromise<void> {
    return $Call.ByID(1206571739, id);
}

// Private type creation functions
const $$createType0 = $models.ModelInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
