// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as memory$0 from "./pkg/memory/models.js";

/**
 * AgentsMdStatus 是会话工作区的 AGENTS.md 发现状态（项目指令记忆的可发现性入口）。
 */
export class AgentsMdStatus {
    "exists": boolean;

    /**
     * Path 是 AGENTS.md 的完整路径（未找到时为预期路径，供 tooltip 展示）。
     */
    "path": string;

    /** Creates a new AgentsMdStatus instance. */
    constructor($$source: Partial<AgentsMdStatus> = {}) {
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentsMdStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentsMdStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentsMdStatus($$parsedSource as Partial<AgentsMdStatus>);
    }
}

/**
 * FileEntry represents a single file or directory in the workspace file tree.
 */
export class FileEntry {
    "name": string;

    /**
     * path relative to workspace root
     */
    "path": string;
    "isDir": boolean;

    /**
     * file size in bytes (0 for dirs)
     */
    "size": number;
    "children"?: FileEntry[];

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField4_0($$parsedSource["children"]);
        }
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

/**
 * MemoryAuditView 是记忆审计视图：归档（forget/覆盖旧值）+ 拒绝（候选审计）。
 */
export class MemoryAuditView {
    "archived": (memory$0.Fact | null)[];
    "rejected": (memory$0.Fact | null)[];

    /** Creates a new MemoryAuditView instance. */
    constructor($$source: Partial<MemoryAuditView> = {}) {
        if (!("archived" in $$source)) {
            this["archived"] = [];
        }
        if (!("rejected" in $$source)) {
            this["rejected"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryAuditView instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryAuditView {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("archived" in $$parsedSource) {
            $$parsedSource["archived"] = $$createField0_0($$parsedSource["archived"]);
        }
        if ("rejected" in $$parsedSource) {
            $$parsedSource["rejected"] = $$createField1_0($$parsedSource["rejected"]);
        }
        return new MemoryAuditView($$parsedSource as Partial<MemoryAuditView>);
    }
}

/**
 * MemoryFactsView 是设置页记忆面板的完整视图：全局记忆 + 各项目记忆。
 */
export class MemoryFactsView {
    "global": (memory$0.Fact | null)[];
    "projects": ProjectMemoryFacts[];

    /** Creates a new MemoryFactsView instance. */
    constructor($$source: Partial<MemoryFactsView> = {}) {
        if (!("global" in $$source)) {
            this["global"] = [];
        }
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryFactsView instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryFactsView {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("global" in $$parsedSource) {
            $$parsedSource["global"] = $$createField0_0($$parsedSource["global"]);
        }
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField1_0($$parsedSource["projects"]);
        }
        return new MemoryFactsView($$parsedSource as Partial<MemoryFactsView>);
    }
}

/**
 * ModelChangedEvent is the payload of the "model:changed" event.
 */
export class ModelChangedEvent {
    "model": ModelInfo;

    /** Creates a new ModelChangedEvent instance. */
    constructor($$source: Partial<ModelChangedEvent> = {}) {
        if (!("model" in $$source)) {
            this["model"] = (new ModelInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelChangedEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelChangedEvent {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("model" in $$parsedSource) {
            $$parsedSource["model"] = $$createField0_0($$parsedSource["model"]);
        }
        return new ModelChangedEvent($$parsedSource as Partial<ModelChangedEvent>);
    }
}

/**
 * ModelInfo describes one configured model entry.
 */
export class ModelInfo {
    /**
     * 配置条目 ID（models[].entryId）
     */
    "entryId": string;

    /**
     * 供应商 ID
     */
    "provider": string;

    /**
     * 供应商类型（gemini/openai）
     */
    "providerType": string;

    /**
     * 发送给 API 的真实模型名
     */
    "modelId": string;

    /**
     * 上下文窗口大小（tokens），0 = 未知
     */
    "contextWindow": number;

    /**
     * 是否为当前使用中的模型
     */
    "active": boolean;

    /**
     * 能力声明（前端门控用：图片入口显隐、推理 UI 等）。
     * 模型支持推理/思考过程
     */
    "supportsReasoning": boolean;

    /**
     * 模型可接收图片输入
     */
    "supportsImages": boolean;

    /**
     * 模型可调用工具
     */
    "supportsTools": boolean;

    /** Creates a new ModelInfo instance. */
    constructor($$source: Partial<ModelInfo> = {}) {
        if (!("entryId" in $$source)) {
            this["entryId"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("providerType" in $$source)) {
            this["providerType"] = "";
        }
        if (!("modelId" in $$source)) {
            this["modelId"] = "";
        }
        if (!("contextWindow" in $$source)) {
            this["contextWindow"] = 0;
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("supportsReasoning" in $$source)) {
            this["supportsReasoning"] = false;
        }
        if (!("supportsImages" in $$source)) {
            this["supportsImages"] = false;
        }
        if (!("supportsTools" in $$source)) {
            this["supportsTools"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelInfo($$parsedSource as Partial<ModelInfo>);
    }
}

/**
 * ModelPrice 是单个模型条目的价格表（元/百万 tokens）。
 */
export class ModelPrice {
    "input": number;
    "output": number;

    /** Creates a new ModelPrice instance. */
    constructor($$source: Partial<ModelPrice> = {}) {
        if (!("input" in $$source)) {
            this["input"] = 0;
        }
        if (!("output" in $$source)) {
            this["output"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelPrice instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelPrice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelPrice($$parsedSource as Partial<ModelPrice>);
    }
}

/**
 * ProjectMemoryFacts 是一个项目级记忆的展示分组。
 */
export class ProjectMemoryFacts {
    "projectId": string;
    "title": string;
    "facts": (memory$0.Fact | null)[];

    /**
     * Candidates 是压缩联动产出的待采纳建议（采纳制：不生效，用户决定）。
     */
    "candidates": (memory$0.Fact | null)[];

    /** Creates a new ProjectMemoryFacts instance. */
    constructor($$source: Partial<ProjectMemoryFacts> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("facts" in $$source)) {
            this["facts"] = [];
        }
        if (!("candidates" in $$source)) {
            this["candidates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectMemoryFacts instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectMemoryFacts {
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("facts" in $$parsedSource) {
            $$parsedSource["facts"] = $$createField2_0($$parsedSource["facts"]);
        }
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField3_0($$parsedSource["candidates"]);
        }
        return new ProjectMemoryFacts($$parsedSource as Partial<ProjectMemoryFacts>);
    }
}

/**
 * SessionStats 是会话级聚合统计，供底部状态栏展示。
 * 轮次级指标（本次命中率/本次费用/tokens/耗时）随每条 assistant 消息的
 * Usage/ElapsedMs 持久化，由前端在消息底部直接渲染，不在此聚合。
 */
export class SessionStats {
    /**
     * Rounds 会话轮次（user 消息数）。
     */
    "rounds": number;

    /**
     * TotalTokens 会话累计 token（所有 assistant 回复合计）。
     */
    "totalTokens": number;

    /**
     * TotalCredits 会话累计 Credits（1 credit = 1000 tokens，直观量级指标）。
     */
    "totalCredits": number;

    /**
     * TotalCostYuan 会话累计费用（元），按各轮模型条目的价格表估算。
     */
    "totalCostYuan": number;

    /**
     * AvgCacheHitRate 会话平均缓存命中率 = Σcached / Σprompt（0-1）。
     */
    "avgCacheHitRate": number;

    /**
     * ContextUsage 上下文使用占比 = 最近一次请求的 promptTokens / ContextWindow（0-1）。
     */
    "contextUsage": number;

    /**
     * ContextWindow 模型上下文窗口（tokens），供前端展示 "x/y" 形式。
     */
    "contextWindow": number;

    /**
     * CompressionThreshold 压缩阈值配置（0-1）。
     */
    "compressionThreshold": number;

    /**
     * CompressionKeepTurns 压缩时保留的最近完整轮数。
     */
    "compressionKeepTurns": number;

    /**
     * CompressionMinBatch 最小压缩集消息数（低于则不压）。
     */
    "compressionMinBatch": number;

    /**
     * CompressionMaxFailures 熔断阈值（连续压缩失败次数）。
     */
    "compressionMaxFailures": number;

    /**
     * CompressionCount 本会话累计压缩次数（从压缩态直读，plan/context 06 篇）。
     */
    "compressionCount": number;

    /**
     * LastCompressionRecovery 上次压缩的回收率（1 - after/before）。
     */
    "lastCompressionRecovery"?: number;

    /**
     * 当前激活模型的价格表，透传给前端计算每条消息的"本次费用"。
     */
    "inputPricePerMillion": number;
    "outputPricePerMillion": number;

    /**
     * ModelPrices 全部模型条目的价格表（key = 条目 ID）：
     * 前端按每条消息的 usage.entryId 核算单条费用；
     * 条目被删除时回退激活模型价格（费用是估算值而非账单）。
     */
    "modelPrices"?: { [_ in string]?: ModelPrice };

    /** Creates a new SessionStats instance. */
    constructor($$source: Partial<SessionStats> = {}) {
        if (!("rounds" in $$source)) {
            this["rounds"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }
        if (!("totalCredits" in $$source)) {
            this["totalCredits"] = 0;
        }
        if (!("totalCostYuan" in $$source)) {
            this["totalCostYuan"] = 0;
        }
        if (!("avgCacheHitRate" in $$source)) {
            this["avgCacheHitRate"] = 0;
        }
        if (!("contextUsage" in $$source)) {
            this["contextUsage"] = 0;
        }
        if (!("contextWindow" in $$source)) {
            this["contextWindow"] = 0;
        }
        if (!("compressionThreshold" in $$source)) {
            this["compressionThreshold"] = 0;
        }
        if (!("compressionKeepTurns" in $$source)) {
            this["compressionKeepTurns"] = 0;
        }
        if (!("compressionMinBatch" in $$source)) {
            this["compressionMinBatch"] = 0;
        }
        if (!("compressionMaxFailures" in $$source)) {
            this["compressionMaxFailures"] = 0;
        }
        if (!("compressionCount" in $$source)) {
            this["compressionCount"] = 0;
        }
        if (!("inputPricePerMillion" in $$source)) {
            this["inputPricePerMillion"] = 0;
        }
        if (!("outputPricePerMillion" in $$source)) {
            this["outputPricePerMillion"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionStats instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionStats {
        const $$createField15_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modelPrices" in $$parsedSource) {
            $$parsedSource["modelPrices"] = $$createField15_0($$parsedSource["modelPrices"]);
        }
        return new SessionStats($$parsedSource as Partial<SessionStats>);
    }
}

/**
 * SubmitResult 是 SubmitMessage 的返回：后端为本轮分配的两条消息 ID。
 * 前端据此回填本地占位消息，DeleteMessage 等按 ID 操作无需等待会话重载。
 */
export class SubmitResult {
    "userMessageId": string;
    "assistantMessageId": string;

    /** Creates a new SubmitResult instance. */
    constructor($$source: Partial<SubmitResult> = {}) {
        if (!("userMessageId" in $$source)) {
            this["userMessageId"] = "";
        }
        if (!("assistantMessageId" in $$source)) {
            this["assistantMessageId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubmitResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SubmitResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubmitResult($$parsedSource as Partial<SubmitResult>);
    }
}

/**
 * WorkspaceInfo describes the current workspace state of a session.
 */
export class WorkspaceInfo {
    /**
     * Path is the effective workspace directory path.
     */
    "path": string;

    /**
     * Name is the base name of the workspace directory, for display.
     */
    "name": string;

    /** Creates a new WorkspaceInfo instance. */
    constructor($$source: Partial<WorkspaceInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceInfo($$parsedSource as Partial<WorkspaceInfo>);
    }
}

// Private type creation functions
const $$createType0 = FileEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = memory$0.Fact.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ProjectMemoryFacts.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ModelInfo.createFrom;
const $$createType8 = ModelPrice.createFrom;
const $$createType9 = $Create.Map($Create.Any, $$createType8);
