// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillService —— 技能库管理（设置页技能页签：安装/启用/分类/检索/制品选择）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skill$0 from "./pkg/skill/models.js";

/**
 * InstallSkill installs a skill from a local artifact (SKILL.md file,
 * directory, or .zip/.tar.gz archive). Returns the installed skill name.
 */
export function InstallSkill(srcPath: string, category: string, overwrite: boolean): $CancellablePromise<string> {
    return $Call.ByID(1796067384, srcPath, category, overwrite);
}

/**
 * ListSkills returns all installed skills (frontmatter + registry metadata).
 */
export function ListSkills(): $CancellablePromise<(skill$0.SkillMeta | null)[]> {
    return $Call.ByID(3092932122).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OpenSkillDirDialog shows the OS native picker for a skill artifact DIRECTORY.
 * Returns the selected path (empty if cancelled).
 */
export function OpenSkillDirDialog(): $CancellablePromise<string> {
    return $Call.ByID(2188832156);
}

/**
 * OpenSkillFileDialog shows the OS native picker for a skill artifact FILE
 * (SKILL.md, .zip, or .tar.gz). Returns the selected path (empty if cancelled).
 * 独立于目录对话框：Windows 原生对话框启用"仅文件夹"模式后无法同时显示文件。
 */
export function OpenSkillFileDialog(): $CancellablePromise<string> {
    return $Call.ByID(4007828839);
}

/**
 * SearchSkills searches installed skills by natural-language query — the same
 * bleve retrieval and result limit as the agent-facing discover_tools tool,
 * so the settings page shows exactly what the model would get. An empty query
 * returns the full list.
 */
export function SearchSkills(query: string): $CancellablePromise<(skill$0.SkillMeta | null)[]> {
    return $Call.ByID(768929118, query).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SetSkillCategory updates an installed skill's category (registry + index
 * regeneration; takes effect in the next conversation turn).
 */
export function SetSkillCategory(name: string, category: string): $CancellablePromise<void> {
    return $Call.ByID(3446419361, name, category);
}

/**
 * SetSkillEnabled enables/disables an installed skill (registry + index
 * regeneration; a disabled skill is invisible to the agent: excluded from
 * the index, discovery search and load_skill).
 */
export function SetSkillEnabled(name: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3779506510, name, enabled);
}

/**
 * SkillCategories returns the distinct categories seen in the registry,
 * for the install dialog's category dropdown.
 */
export function SkillCategories(): $CancellablePromise<string[]> {
    return $Call.ByID(510098845).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * UninstallSkill removes an installed skill (directory + registry entry)
 * and regenerates the index.
 */
export function UninstallSkill(name: string): $CancellablePromise<void> {
    return $Call.ByID(3919044539, name);
}

// Private type creation functions
const $$createType0 = skill$0.SkillMeta.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
