// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StatService —— 会话聚合统计（底部状态栏：tokens/费用/缓存命中/压缩计量）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSessionStats 返回指定会话的聚合统计。空会话返回带模型/价格信息的零值。
 */
export function GetSessionStats(sessionID: string): $CancellablePromise<$models.SessionStats | null> {
    return $Call.ByID(3579778870, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SessionStats.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
