// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService —— 工作区目录查询与换绑（目录选择对话框 + 项目级工作区守卫）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetWorkspaceInfo returns the current workspace info for a session.
 */
export function GetWorkspaceInfo(sessionID: string): $CancellablePromise<$models.WorkspaceInfo | null> {
    return $Call.ByID(3857467001, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenDirectoryDialog shows the OS native directory picker and returns the
 * selected path (empty string if the user cancels). This does NOT change the
 * session's workspace — call SetWorkspaceDir to apply the selection.
 */
export function OpenDirectoryDialog(): $CancellablePromise<string> {
    return $Call.ByID(3707212607);
}

/**
 * SetWorkspaceDir sets a custom workspace directory for the given session's
 * PROJECT（工作区是项目属性：同项目全部会话共享）。守卫在 App 层：
 * 项目内所有会话零消息且无运行中的轮才允许；锁定后不迁移。
 * 不存在"重置为默认"入口。
 */
export function SetWorkspaceDir(sessionID: string, dir: string): $CancellablePromise<void> {
    return $Call.ByID(1874990820, sessionID, dir);
}

// Private type creation functions
const $$createType0 = $models.WorkspaceInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
