// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config 是记忆功能配置段（AppConfig.memory；8.5）。
 */
export class Config {
    /**
     * Enabled 为 false 时记忆块不注入、remember/recall 报错。
     * 缺省 true（见 UnmarshalYAML：旧配置无此键不能静默关闭功能）。
     */
    "enabled": boolean;
    "maxIndexBytes"?: number;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * Fact 是一条记忆事实：一事实一文件（<root>/<subject>.md），
 * frontmatter 承载元数据，正文一两句话。
 */
export class Fact {
    "type": FactType;

    /**
     * 主题键：同 root 内唯一活跃值（文件名锚）
     */
    "subject": string;

    /**
     * 2006-01-02
     */
    "created": string;
    "lastConfirmed": string;

    /**
     * 空 = 不过期；到期排除出索引与召回（软遗忘，不删除）
     */
    "expiresAt"?: string;

    /**
     * user / archive://...（溯源）
     */
    "source": string;

    /**
     * 来源模型条目 ID（防模型特化记忆污染）
     */
    "writtenBy"?: string;
    "body": string;

    /** Creates a new Fact instance. */
    constructor($$source: Partial<Fact> = {}) {
        if (!("type" in $$source)) {
            this["type"] = FactType.$zero;
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }
        if (!("lastConfirmed" in $$source)) {
            this["lastConfirmed"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Fact instance from a string or object.
     */
    static createFrom($$source: any = {}): Fact {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Fact($$parsedSource as Partial<Fact>);
    }
}

/**
 * FactType 事实类型（plan/agent-memory-design-plan.md §3.1）：
 * 四类陈述性事实 + lesson（过程性知识暂存，毕业后归 write_skill）。
 */
export enum FactType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FactUser = "user",
    FactFeedback = "feedback",
    FactProject = "project",
    FactReference = "reference",
    FactLesson = "lesson",
};
