// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../../tars/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "agent:chunk": main$0.StreamChunk;
            "agent:done": main$0.StreamDone;
            "agent:error": main$0.StreamError;
            "agent:reasoning": main$0.ReasoningEvent;
            "agent:tool": main$0.ToolEvent;
            "agent:tool_result": main$0.ToolResultEvent;
            "conversation:renamed": main$0.ConversationRenamedEvent;
        }
    }
}
