//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../../tars/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "agent:chunk": $$createType0,
        "agent:done": $$createType1,
        "agent:error": $$createType2,
        "agent:reasoning": $$createType3,
        "agent:tool": $$createType4,
        "agent:tool_result": $$createType5,
        "conversation:renamed": $$createType6,
        "model:changed": $$createType7,
        "workspace:changed": $$createType8,
    }));
}

// Private type creation functions
const $$createType0 = main$0.StreamChunk.createFrom;
const $$createType1 = main$0.StreamDone.createFrom;
const $$createType2 = main$0.StreamError.createFrom;
const $$createType3 = main$0.ReasoningEvent.createFrom;
const $$createType4 = main$0.ToolEvent.createFrom;
const $$createType5 = main$0.ToolResultEvent.createFrom;
const $$createType6 = main$0.ConversationRenamedEvent.createFrom;
const $$createType7 = main$0.ModelChangedEvent.createFrom;
const $$createType8 = main$0.WorkspaceChangedEvent.createFrom;

configure();
