// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../../tars/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as event$0 from "../../../../../tars/internal/event/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "agent:approval": event$0.ApprovalEvent | null;
            "agent:chunk": event$0.StreamChunk | null;
            "agent:done": event$0.StreamDone | null;
            "agent:error": event$0.StreamError | null;
            "agent:reasoning": event$0.ReasoningEvent | null;
            "agent:tool": event$0.ToolEvent | null;
            "agent:tool_result": event$0.ToolResultEvent | null;
            "model:changed": main$0.ModelChangedEvent | null;
            "session:renamed": event$0.SessionRenamedEvent | null;
            "workspace:changed": event$0.WorkspaceChangedEvent | null;
        }
    }
}
