// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "../schema/models.js";

/**
 * ApprovalEvent "agent:approval"：执行层拦截危险工具调用后发起的安全审批请求。
 * 答复键即 ToolCallID；答复经 AgentService.AnswerAskUser 回写，
 * 终态（允许/拒绝/超时默认拒绝）随 agent:tool_result 到达。
 */
export class ApprovalEvent {
    "sessionId": string;
    "toolCallId": string;
    "toolName": string;

    /**
     * 待批准的危险内容（如完整命令）
     */
    "summary": string;

    /**
     * 命中的风险规则说明
     */
    "reason": string;
    "timeoutSeconds": number;

    /** Creates a new ApprovalEvent instance. */
    constructor($$source: Partial<ApprovalEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("toolCallId" in $$source)) {
            this["toolCallId"] = "";
        }
        if (!("toolName" in $$source)) {
            this["toolName"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("timeoutSeconds" in $$source)) {
            this["timeoutSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApprovalEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ApprovalEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApprovalEvent($$parsedSource as Partial<ApprovalEvent>);
    }
}

/**
 * CompressionDoneEvent "session:compression_done"：一次压缩完成。
 */
export class CompressionDoneEvent {
    "sessionId": string;

    /**
     * 压缩前实测
     */
    "beforeTokens": number;

    /**
     * 压缩后估算（bytes/4）
     */
    "afterTokens": number;

    /**
     * 本次新增归档条目数
     */
    "newEntries": number;

    /**
     * 条目总数
     */
    "totalEntries": number;
    "durationMs": number;

    /** Creates a new CompressionDoneEvent instance. */
    constructor($$source: Partial<CompressionDoneEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("beforeTokens" in $$source)) {
            this["beforeTokens"] = 0;
        }
        if (!("afterTokens" in $$source)) {
            this["afterTokens"] = 0;
        }
        if (!("newEntries" in $$source)) {
            this["newEntries"] = 0;
        }
        if (!("totalEntries" in $$source)) {
            this["totalEntries"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompressionDoneEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): CompressionDoneEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompressionDoneEvent($$parsedSource as Partial<CompressionDoneEvent>);
    }
}

/**
 * CompressionFailedEvent "session:compression_failed"：压缩失败；
 * 连续失败达熔断阈值时 CircuitOpen=true（本会话不再自动压缩）。
 */
export class CompressionFailedEvent {
    "sessionId": string;
    "error": string;
    "failures": number;
    "circuitOpen": boolean;

    /** Creates a new CompressionFailedEvent instance. */
    constructor($$source: Partial<CompressionFailedEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("failures" in $$source)) {
            this["failures"] = 0;
        }
        if (!("circuitOpen" in $$source)) {
            this["circuitOpen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompressionFailedEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): CompressionFailedEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompressionFailedEvent($$parsedSource as Partial<CompressionFailedEvent>);
    }
}

/**
 * CompressionStartedEvent "session:compression_started"：压缩管线触发并开始执行。
 */
export class CompressionStartedEvent {
    "sessionId": string;

    /**
     * 触发时的实测 prompt tokens
     */
    "triggerTokens": number;

    /**
     * 阈值预算（ContextWindow × threshold）
     */
    "budget": number;

    /** Creates a new CompressionStartedEvent instance. */
    constructor($$source: Partial<CompressionStartedEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("triggerTokens" in $$source)) {
            this["triggerTokens"] = 0;
        }
        if (!("budget" in $$source)) {
            this["budget"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompressionStartedEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): CompressionStartedEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompressionStartedEvent($$parsedSource as Partial<CompressionStartedEvent>);
    }
}

/**
 * ReasoningEvent "agent:reasoning"：思考链内容的流式增量片段。
 */
export class ReasoningEvent {
    "sessionId": string;
    "messageId": string;
    "content": string;

    /** Creates a new ReasoningEvent instance. */
    constructor($$source: Partial<ReasoningEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReasoningEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ReasoningEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReasoningEvent($$parsedSource as Partial<ReasoningEvent>);
    }
}

/**
 * SessionRenamedEvent "session:renamed"：会话标题变更（手动或首条消息自动命名）。
 */
export class SessionRenamedEvent {
    "sessionId": string;
    "title": string;

    /** Creates a new SessionRenamedEvent instance. */
    constructor($$source: Partial<SessionRenamedEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionRenamedEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionRenamedEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionRenamedEvent($$parsedSource as Partial<SessionRenamedEvent>);
    }
}

/**
 * StreamChunk "agent:chunk"：assistant 正文内容的流式增量片段。
 */
export class StreamChunk {
    "sessionId": string;
    "messageId": string;
    "chunk": string;

    /** Creates a new StreamChunk instance. */
    constructor($$source: Partial<StreamChunk> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("chunk" in $$source)) {
            this["chunk"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamChunk instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamChunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamChunk($$parsedSource as Partial<StreamChunk>);
    }
}

/**
 * StreamDone "agent:done"：一轮正常结束（含用户取消的干净停止）。
 */
export class StreamDone {
    "sessionId": string;
    "messageId": string;
    "usage"?: schema$0.UsageInfo | null;
    "elapsedMs": number;

    /** Creates a new StreamDone instance. */
    constructor($$source: Partial<StreamDone> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamDone instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamDone {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField2_0($$parsedSource["usage"]);
        }
        return new StreamDone($$parsedSource as Partial<StreamDone>);
    }
}

/**
 * StreamError "agent:error"：一轮以错误结束；kind 区分超时与普通错误。
 */
export class StreamError {
    "sessionId": string;
    "messageId": string;
    "error": string;
    "kind"?: string;

    /** Creates a new StreamError instance. */
    constructor($$source: Partial<StreamError> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamError instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamError($$parsedSource as Partial<StreamError>);
    }
}

/**
 * ToolEvent "agent:tool"：一个工具调用开始执行。
 */
export class ToolEvent {
    "sessionId": string;
    "messageId": string;
    "toolCallId": string;
    "toolName": string;
    "args": string;

    /** Creates a new ToolEvent instance. */
    constructor($$source: Partial<ToolEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("toolCallId" in $$source)) {
            this["toolCallId"] = "";
        }
        if (!("toolName" in $$source)) {
            this["toolName"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolEvent($$parsedSource as Partial<ToolEvent>);
    }
}

/**
 * ToolResultEvent "agent:tool_result"：一个工具调用执行完成。
 */
export class ToolResultEvent {
    "sessionId": string;
    "messageId": string;
    "toolCallId": string;
    "output": string;

    /** Creates a new ToolResultEvent instance. */
    constructor($$source: Partial<ToolResultEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("toolCallId" in $$source)) {
            this["toolCallId"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolResultEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolResultEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolResultEvent($$parsedSource as Partial<ToolResultEvent>);
    }
}

// Private type creation functions
const $$createType0 = schema$0.UsageInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
