// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Risk 级别：MCP 工具默认 RiskMedium（走审批流），可按服务器覆盖。
 */
export enum Risk {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 只读查询，不触发审批
     */
    RiskLow = "low",

    /**
     * 默认：执行前需用户审批
     */
    RiskMedium = "medium",

    /**
     * 同 medium，GUI 中醒目标注
     */
    RiskHigh = "high",
};

/**
 * ServerConfig 是一个 MCP 服务器（本地 stdio 进程）的配置。
 * 能力默认关闭（Enabled 零值 false），须显式启用（失败安全默认值）。
 */
export class ServerConfig {
    /**
     * Command 是服务器可执行文件（或 npx/uvx 等启动器）。
     */
    "command": string;

    /**
     * Args 是启动参数。
     */
    "args"?: string[];

    /**
     * Env 是附加环境变量（最小权限凭证；支持 ${VAR} 引用，进程拉起时展开——
     * 磁盘与内存配置中引用原样保留，写回不泄露密钥）。
     */
    "env"?: { [_ in string]?: string };

    /**
     * Description 是一句话能力描述（服务器级索引用，模型可见，用英文）。
     */
    "description"?: string;

    /**
     * SourceType 是信息源类型标注（search/read/parse/query，自由文本）。
     */
    "sourceType"?: string;

    /**
     * Enabled 为 false 时服务器对 Agent 不可见且不启动进程（默认关闭）。
     */
    "enabled"?: boolean;

    /**
     * Risk 是该服务器全部工具的默认风险级别（空值归一为 medium）。
     */
    "risk"?: Risk;

    /** Creates a new ServerConfig instance. */
    constructor($$source: Partial<ServerConfig> = {}) {
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerConfig {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField1_0($$parsedSource["args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField2_0($$parsedSource["env"]);
        }
        return new ServerConfig($$parsedSource as Partial<ServerConfig>);
    }
}

/**
 * ServerInfo 是一个 MCP 服务器的展示视图（配置快照，指针不共享）。
 */
export class ServerInfo {
    "name": string;
    "command": string;
    "description": string;
    "sourceType": string;
    "enabled": boolean;
    "risk": Risk;

    /**
     * 探测缓存中的工具数（#3 填充；0 表示未探测）
     */
    "toolCount": number;

    /** Creates a new ServerInfo instance. */
    constructor($$source: Partial<ServerInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("sourceType" in $$source)) {
            this["sourceType"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("risk" in $$source)) {
            this["risk"] = Risk.$zero;
        }
        if (!("toolCount" in $$source)) {
            this["toolCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerInfo($$parsedSource as Partial<ServerInfo>);
    }
}

/**
 * ToolInfo 是一个 MCP 工具的缓存视图（探测时抓取；模型可见文本均为英文）。
 */
export class ToolInfo {
    "name": string;
    "description"?: string;

    /**
     * InputSchema 是工具的 JSON Schema（原样缓存；#6 检索、#7 包装 Definition
     * 时直接作为 schema.ToolSchema.Parameters 使用）。
     */
    "inputSchema"?: { [_ in string]?: any };

    /** Creates a new ToolInfo instance. */
    constructor($$source: Partial<ToolInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolInfo {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputSchema" in $$parsedSource) {
            $$parsedSource["inputSchema"] = $$createField2_0($$parsedSource["inputSchema"]);
        }
        return new ToolInfo($$parsedSource as Partial<ToolInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
