// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "../../../github.com/cloudwego/eino/schema/models.js";

/**
 * Message is one line in messages.jsonl. 本类型是会话消息的唯一权威定义：
 * 磁盘格式、内存形态、前端 API 共用，internal/session 以类型别名直接复用
 * （session.Message = store.Message）。
 */
export class Message {
    "id": string;
    "role": schema$0.RoleType;
    "content": string;
    "toolCalls"?: ToolCall[];
    "toolCallId"?: string;
    "createdAt": number;

    /**
     * Reasoning 仅 assistant 消息有值：模型思考过程（thinking/reasoning
     * content），多轮迭代时逐轮累加。
     */
    "reasoning"?: string;

    /**
     * Usage/ElapsedMs 仅 assistant 消息有值：本轮 token 消耗与总耗时。
     */
    "usage"?: UsageInfo | null;
    "elapsedMs"?: number;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = schema$0.RoleType.$zero;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField3_0 = $$createType1;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolCalls" in $$parsedSource) {
            $$parsedSource["toolCalls"] = $$createField3_0($$parsedSource["toolCalls"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField7_0($$parsedSource["usage"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

/**
 * ToolCall is a single tool invocation within an assistant message.
 */
export class ToolCall {
    "id": string;
    "name": string;
    "args": string;

    /** Creates a new ToolCall instance. */
    constructor($$source: Partial<ToolCall> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCall instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCall {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCall($$parsedSource as Partial<ToolCall>);
    }
}

/**
 * UsageInfo 一次 assistant 回复的 token 统计。
 */
export class UsageInfo {
    "promptTokens": number;
    "completionTokens": number;
    "totalTokens": number;
    "cachedTokens"?: number;

    /**
     * ModelEntry 产生该用量的模型条目 ID，多模型下按条目价格表核算费用
     */
    "modelEntry"?: string;

    /** Creates a new UsageInfo instance. */
    constructor($$source: Partial<UsageInfo> = {}) {
        if (!("promptTokens" in $$source)) {
            this["promptTokens"] = 0;
        }
        if (!("completionTokens" in $$source)) {
            this["completionTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageInfo($$parsedSource as Partial<UsageInfo>);
    }
}

// Private type creation functions
const $$createType0 = ToolCall.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = UsageInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
