// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "../../../github.com/cloudwego/eino/schema/models.js";

export class Message {
    "id": string;
    "role": schema$0.RoleType;
    "content": string;
    "toolCalls"?: ToolCall[];
    "toolCallId"?: string;
    "createdAt": number;
    "reasoning"?: string;
    "usage"?: UsageInfo | null;
    "elapsedMs"?: number;

    /**
     * Parts 按 ReAct 迭代记录 assistant 消息的产出顺序（仅 assistant 角色）。
     */
    "parts"?: MessagePart[];

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = schema$0.RoleType.$zero;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField3_0 = $$createType1;
        const $$createField7_0 = $$createType3;
        const $$createField9_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolCalls" in $$parsedSource) {
            $$parsedSource["toolCalls"] = $$createField3_0($$parsedSource["toolCalls"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField7_0($$parsedSource["usage"]);
        }
        if ("parts" in $$parsedSource) {
            $$parsedSource["parts"] = $$createField9_0($$parsedSource["parts"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

/**
 * MessagePart 是 assistant 消息在一个 ReAct 迭代内的产出：本轮文本 + 工具调用。
 * 前端据此把各迭代的文本与工具卡片按时间顺序交错渲染；
 * Content/ToolCalls 聚合字段（全迭代拼接）继续供 LLM 上下文、导出与统计使用。
 */
export class MessagePart {
    "content"?: string;
    "toolCalls"?: ToolCall[];

    /** Creates a new MessagePart instance. */
    constructor($$source: Partial<MessagePart> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessagePart instance from a string or object.
     */
    static createFrom($$source: any = {}): MessagePart {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolCalls" in $$parsedSource) {
            $$parsedSource["toolCalls"] = $$createField1_0($$parsedSource["toolCalls"]);
        }
        return new MessagePart($$parsedSource as Partial<MessagePart>);
    }
}

export class ToolCall {
    "id": string;
    "name": string;
    "args": string;

    /** Creates a new ToolCall instance. */
    constructor($$source: Partial<ToolCall> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCall instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCall {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCall($$parsedSource as Partial<ToolCall>);
    }
}

export class UsageInfo {
    "promptTokens": number;
    "completionTokens": number;
    "totalTokens": number;
    "cachedTokens"?: number;
    "modelEntry"?: string;

    /** Creates a new UsageInfo instance. */
    constructor($$source: Partial<UsageInfo> = {}) {
        if (!("promptTokens" in $$source)) {
            this["promptTokens"] = 0;
        }
        if (!("completionTokens" in $$source)) {
            this["completionTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageInfo($$parsedSource as Partial<UsageInfo>);
    }
}

// Private type creation functions
const $$createType0 = ToolCall.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = UsageInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = MessagePart.createFrom;
const $$createType5 = $Create.Array($$createType4);
