// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as llm$0 from "../../pkg/llm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skills$0 from "../../pkg/skills/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as trace$0 from "../../pkg/trace/models.js";

/**
 * AppConfig 是用户应用配置（config.yaml）。
 * 注意：MCP 服务器配置不属于本结构——它与技能一样由 pkg/mcp.Manager
 * 在工作目录（<workDir>/mcp/servers.yaml）下自管读写、即改即存。
 */
export class AppConfig {
    "llm"?: llm$0.Config | null;
    "workDir"?: string;
    "trace"?: trace$0.Config | null;
    "agent"?: agent$0.Config | null;
    "skills"?: skills$0.Config | null;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        const $$createField0_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType5;
        const $$createField4_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("llm" in $$parsedSource) {
            $$parsedSource["llm"] = $$createField0_0($$parsedSource["llm"]);
        }
        if ("trace" in $$parsedSource) {
            $$parsedSource["trace"] = $$createField2_0($$parsedSource["trace"]);
        }
        if ("agent" in $$parsedSource) {
            $$parsedSource["agent"] = $$createField3_0($$parsedSource["agent"]);
        }
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField4_0($$parsedSource["skills"]);
        }
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

// Private type creation functions
const $$createType0 = llm$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = trace$0.Config.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = agent$0.Config.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = skills$0.Config.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
