// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RoleType is the type of the role of a message.
 */
export enum RoleType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Assistant is the role of an assistant, means the message is returned by ChatModel.
     */
    Assistant = "assistant",

    /**
     * User is the role of a user, means the message is a user message.
     */
    User = "user",

    /**
     * System is the role of a system, means the message is a system message.
     */
    System = "system",

    /**
     * Tool is the role of a tool, means the message is a tool call output.
     */
    Tool = "tool",
};
