// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../../pkg/store/models.js";

/**
 * ReasoningEvent "agent:reasoning"：思考链内容的流式增量片段。
 */
export class ReasoningEvent {
    "sessionId": string;
    "messageId": string;
    "content": string;

    /** Creates a new ReasoningEvent instance. */
    constructor($$source: Partial<ReasoningEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReasoningEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ReasoningEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReasoningEvent($$parsedSource as Partial<ReasoningEvent>);
    }
}

/**
 * SessionRenamedEvent "session:renamed"：会话标题变更（手动或首条消息自动命名）。
 */
export class SessionRenamedEvent {
    "sessionId": string;
    "title": string;

    /** Creates a new SessionRenamedEvent instance. */
    constructor($$source: Partial<SessionRenamedEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionRenamedEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionRenamedEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionRenamedEvent($$parsedSource as Partial<SessionRenamedEvent>);
    }
}

/**
 * StreamChunk "agent:chunk"：assistant 正文内容的流式增量片段。
 */
export class StreamChunk {
    "sessionId": string;
    "messageId": string;
    "chunk": string;

    /** Creates a new StreamChunk instance. */
    constructor($$source: Partial<StreamChunk> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("chunk" in $$source)) {
            this["chunk"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamChunk instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamChunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamChunk($$parsedSource as Partial<StreamChunk>);
    }
}

/**
 * StreamDone "agent:done"：一轮正常结束（含用户取消的干净停止）。
 */
export class StreamDone {
    "sessionId": string;
    "messageId": string;
    "usage"?: store$0.UsageInfo | null;
    "elapsedMs": number;

    /** Creates a new StreamDone instance. */
    constructor($$source: Partial<StreamDone> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamDone instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamDone {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField2_0($$parsedSource["usage"]);
        }
        return new StreamDone($$parsedSource as Partial<StreamDone>);
    }
}

/**
 * StreamError "agent:error"：一轮以错误结束；kind 区分超时与普通错误。
 */
export class StreamError {
    "sessionId": string;
    "messageId": string;
    "error": string;
    "kind"?: string;

    /** Creates a new StreamError instance. */
    constructor($$source: Partial<StreamError> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamError instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamError($$parsedSource as Partial<StreamError>);
    }
}

/**
 * ToolEvent "agent:tool"：一个工具调用开始执行。
 */
export class ToolEvent {
    "sessionId": string;
    "messageId": string;
    "toolCallId": string;
    "toolName": string;
    "args": string;

    /** Creates a new ToolEvent instance. */
    constructor($$source: Partial<ToolEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("toolCallId" in $$source)) {
            this["toolCallId"] = "";
        }
        if (!("toolName" in $$source)) {
            this["toolName"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolEvent($$parsedSource as Partial<ToolEvent>);
    }
}

/**
 * ToolResultEvent "agent:tool_result"：一个工具调用执行完成。
 */
export class ToolResultEvent {
    "sessionId": string;
    "messageId": string;
    "toolCallId": string;
    "output": string;

    /** Creates a new ToolResultEvent instance. */
    constructor($$source: Partial<ToolResultEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("toolCallId" in $$source)) {
            this["toolCallId"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolResultEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolResultEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolResultEvent($$parsedSource as Partial<ToolResultEvent>);
    }
}

// Private type creation functions
const $$createType0 = store$0.UsageInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
