// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class Config {
    "maxIterations"?: number;
    "compressionThreshold"?: number;
    "compressionKeepTurns"?: number;
    "compressionMinBatch"?: number;
    "compressionMaxFailures"?: number;
    "iterationTimeout"?: time$0.Duration;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}
