// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Message 是会话中的一条消息（内存态与持久化共用同一结构）。
 * 交错式存储（plan/context 07 篇）：每次 ReAct 迭代一条独立 assistant 消息，
 * 工具结果消息紧随发起它的 assistant 消息、按 ToolCallID 配对。
 */
export class Message {
    "id": string;
    "role": Role;

    /**
     * TurnID 轮分组键：一轮（user 提问 + 其后全部 assistant/tool 消息）内
     * 所有消息共享同一值，取值为该轮 user 消息的 ID（user 消息的
     * TurnID == 自身 ID）。重试复用原 user 消息，故 TurnID 跨重试稳定。
     * 空值 = 旧数据，消费方回退"轮起点 = user 消息"的扫描规则。
     */
    "turnId"?: string;

    /**
     * Iteration 轮内迭代序号（1 起；assistant 消息与其工具结果同号；
     * user 消息为 0）。
     * 
     * 纯展示/诊断元数据，不得作为索引、计数或位置依据：
     *   - 分组只用 TurnID，不用 Iteration；
     *   - 轮内排序只用消息在轨迹中的先后，不用 Iteration 数值；
     *   - 不假设它从 1 开始、连续、或 max == 迭代总数——截断类操作
     *     （删除/重试）与压缩投影都会让它出现缺口或非 1 起始。
     */
    "iteration"?: number;
    "content": string;

    /**
     * Images 用户消息附带的图片（data URL，RFC-2397：data:image/png;base64,...）。
     * 仅 user 消息使用；随消息持久化。压缩链路（提取/归档/体量估算）只读
     * Content/Reasoning/Args 文本，图片数据天然不进入压缩器。
     */
    "images"?: string[];
    "toolCalls"?: ToolCall[];
    "toolCallId"?: string;
    "createdAt": number;
    "reasoning"?: string;
    "usage"?: UsageInfo | null;
    "elapsedMs"?: number;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = Role.$zero;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        const $$createField10_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField5_0($$parsedSource["images"]);
        }
        if ("toolCalls" in $$parsedSource) {
            $$parsedSource["toolCalls"] = $$createField6_0($$parsedSource["toolCalls"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField10_0($$parsedSource["usage"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

/**
 * Role 表示消息的角色。
 */
export enum Role {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleSystem = "system",
    RoleUser = "user",
    RoleAssistant = "assistant",
    RoleTool = "tool",
};

/**
 * ToolCall 是 assistant 消息里的一个工具调用（存储视图：函数名与参数原文拍平）。
 */
export class ToolCall {
    "id": string;
    "name": string;
    "args": string;

    /** Creates a new ToolCall instance. */
    constructor($$source: Partial<ToolCall> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCall instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCall {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCall($$parsedSource as Partial<ToolCall>);
    }
}

/**
 * UsageInfo 是一次助手回复的 token 用量。
 */
export class UsageInfo {
    "promptTokens": number;
    "completionTokens": number;
    "totalTokens": number;
    "cachedTokens"?: number;

    /**
     * EntryID 是产生该用量的本地配置条目 ID（llm.ModelConfig.EntryID，
     * 如 "gemini/gemini-3.1-flash-lite"），用于按条目价格表核算费用；
     * 不是发给 API 的真实模型名（ModelConfig.ModelId）——同一真实模型
     * 可配多个条目、价格不同，故费用按条目核算。
     */
    "entryId"?: string;

    /** Creates a new UsageInfo instance. */
    constructor($$source: Partial<UsageInfo> = {}) {
        if (!("promptTokens" in $$source)) {
            this["promptTokens"] = 0;
        }
        if (!("completionTokens" in $$source)) {
            this["completionTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageInfo($$parsedSource as Partial<UsageInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ToolCall.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = UsageInfo.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
