// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "../../pkg/schema/models.js";

/**
 * Data 是会话的内存数据：会话级元数据 + 消息列表 + 会话级幂等状态。
 * 轮的运行态（取消标记）在 boot.Controller——goroutine 在那里创建。
 */
export class Data {
    "id": string;
    "title": string;
    "createdAt": number;
    "updatedAt": number;
    "workspaceDir": string;
    "messages": (schema$0.Message | null)[];

    /** Creates a new Data instance. */
    constructor($$source: Partial<Data> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }
        if (!("workspaceDir" in $$source)) {
            this["workspaceDir"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Data instance from a string or object.
     */
    static createFrom($$source: any = {}): Data {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField5_0($$parsedSource["messages"]);
        }
        return new Data($$parsedSource as Partial<Data>);
    }
}

// Private type creation functions
const $$createType0 = schema$0.Message.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
