// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../session/models.js";

/**
 * ProjectView 是项目的展示视图：项目元信息 + 其下会话。
 */
export class ProjectView {
    "id": string;

    /**
     * Title 是用户显式命名的项目标题；空 = 未命名（展示层从项目内最近
     * 会话的标题推导）。显式优先：一旦命名，不再跟随会话自动命名。
     */
    "title"?: string;

    /**
     * WorkspaceDir 是用户显式设置的自定义工作区绝对路径；空 = 使用
     * 项目级默认目录（GetWorkspaceDir 解析）。
     */
    "workspaceDir"?: string;
    "createdAt": number;
    "updatedAt": number;
    "sessions": (session$0.Data | null)[];

    /** Creates a new ProjectView instance. */
    constructor($$source: Partial<ProjectView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }
        if (!("sessions" in $$source)) {
            this["sessions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectView instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectView {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField5_0($$parsedSource["sessions"]);
        }
        return new ProjectView($$parsedSource as Partial<ProjectView>);
    }
}

// Private type creation functions
const $$createType0 = session$0.Data.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
